//! Deriving generators for `Eq`, `ToText`, and `Ord` (0.2.13).
//!
//! [`derive_instances`] is the entry point. Given a [`TypeDecl`] and a list of
//! class names from its `deriving` clause, it synthesises one [`DerivedInstance`]
//! per class and registers each into the [`InstanceEnv`] via the same
//! [`InstanceEnv::insert`] path that hand-written instances use — coherence
//! (T032 overlap) is therefore automatic.
//!
//! # Derivable classes (0.2.13)
//!
//! - **`Eq`** — whole-value `=:=` (BEAM structural equality). Near-free for
//!   both records (Erlang maps) and unions (tagged tuples / bare atoms).
//!   **Not** constant-time — see the security note in [`DerivedMethodBody`].
//!   Fails with T029 when any field type is `Float` (floating-point equality
//!   footgun).
//!
//! - **`ToText`** (`Show` is an alias, desugared at parse time) — renders the
//!   value to a human-readable string. Records: field-by-field in declared
//!   order. Unions: constructor name, with payload fields rendered recursively.
//!   Each field/payload dispatch requires a `ToText` instance for that field's
//!   type; those become `ctx_constraints` on the generated instance.
//!
//! - **`Ord`** — lexicographic comparison returning `Ordering`. Records:
//!   field-by-field in declared order, first non-`Equal` wins. Unions: compare
//!   by variant index first, then payload fields if same variant. Requires
//!   `Eq T` (the `Ord` superclass) and `Ord FieldType` for each field.
//!
//! # Integration
//!
//! Derived instances are registered into the same [`InstanceEnv`] as
//! hand-written ones. The constraint solver and dictionary lowering treat them
//! identically. `collect.rs` calls [`derive_instances`] after collecting
//! explicit instances.

use ridge_ast::{
    decl::{Constructor, FieldDecl, TypeBody},
    Ident, Span, Type as AstType,
};
use ridge_types::{Constraint, TyConId, EQ_CLASS, ORD_CLASS, TOTEXT_CLASS};
use rustc_hash::FxHashMap;

use crate::class_env::{ClassTable, InstanceEnv, InstanceInfo, InstanceOrigin};
use crate::error::TypeError;

// ── Public types ──────────────────────────────────────────────────────────────

/// The method body generated by a derive generator.
///
/// In 0.2.13 all three derivable classes use BEAM structural primitives, so
/// the "body" is captured as a symbolic tag that the lowering pass translates
/// into Core Erlang.  The tag carries enough information for the lowering pass
/// to emit the right BEAM expression without re-examining the type.
///
/// # Security note — `DerivedEq`
///
/// The generated `eq` implementation uses `=:=` (BEAM structural equality),
/// which is **not** constant-time. Types that carry secret data (tokens, hashes,
/// HMACs, session keys) must not derive `Eq`; use `Crypto.constantTimeEq`
/// instead. The `@secret` attribute (planned for a later cut) will make this
/// a hard error automatically.
#[derive(Debug, Clone)]
pub enum DerivedMethodBody {
    /// `eq (a: T) (b: T) -> Bool = (a =:= b)` — BEAM structural equality.
    DerivedEq,
    /// `toText` body for a record type. Fields rendered in declared order,
    /// each dispatched through the `toText` method of its type.
    DerivedToTextRecord {
        /// Field names in declaration order.
        field_names: Vec<String>,
        /// `TyConId` of each field's type, in the same order as `field_names`.
        /// Used by the lowering pass to select the correct `toText` dispatch
        /// (e.g. `std.int.toText` for `Int` fields).  `None` when the field
        /// type could not be resolved to a concrete `TyConId` (parametric or
        /// unknown types); the lowering pass emits an identity in that case.
        field_tycons: Vec<Option<TyConId>>,
    },
    /// `toText` body for a union type. Each variant maps to a string; payload
    /// fields are dispatched through `toText`.
    DerivedToTextUnion {
        /// `(ctor_name, payload_field_count, payload_tycons)` in declaration order.
        /// `payload_tycons` carries the `TyConId` for each positional payload
        /// field (same indexing as `payload_field_count`); `None` entries are
        /// treated as identity by the lowering pass.
        variants: Vec<(String, usize, Vec<Option<TyConId>>)>,
    },
    /// `compare` body for a record type. Fields compared in declared order,
    /// first non-`Equal` wins.
    DerivedOrdRecord {
        /// Field names in declaration order.
        field_names: Vec<String>,
    },
    /// `compare` body for a union type. Variants ordered by declaration index;
    /// payloads compared field-by-field when the variant matches.
    DerivedOrdUnion {
        /// `(ctor_name, payload_field_count)` in declaration order.
        variants: Vec<(String, usize)>,
    },
}

/// One generated instance produced by [`derive_instances`].
#[derive(Debug, Clone)]
pub struct DerivedInstance {
    /// The `(ClassId, TyConId)` key this instance covers.
    pub key: (ridge_types::ClassId, TyConId),
    /// The [`InstanceInfo`] registered into [`InstanceEnv`].
    pub instance_info: InstanceInfo,
    /// The synthesised method body (one per instance — each derived class has
    /// exactly one method in 0.2.13).
    pub method_body: DerivedMethodBody,
}

// ── Public entry point ────────────────────────────────────────────────────────

/// Synthesise instances for every class in `type_decl.deriving` and register
/// them into `instance_env`.
///
/// Returns a list of successfully generated [`DerivedInstance`]s and a list of
/// [`TypeError`]s for any class that could not be derived (e.g. unknown class,
/// non-derivable class, `Float` field in `Eq`).
///
/// The `tycon_id` argument is the [`TyConId`] already assigned to this type
/// in the workspace arena. The `module_id` is used as the `def_module` of the
/// generated instance (the instance lives in the same module as the type).
///
/// `user_tycon_names` maps type names to their [`TyConId`]s; used to check
/// whether a field type is `Float` or another concrete type.
#[expect(
    clippy::implicit_hasher,
    reason = "FxHashMap is the canonical hasher for this crate; matches the pattern in solve.rs and collect.rs"
)]
pub fn derive_instances(
    type_decl: &ridge_ast::decl::TypeDecl,
    tycon_id: TyConId,
    module_id: u32,
    class_table: &ClassTable,
    instance_env: &mut InstanceEnv,
    user_tycon_names: &FxHashMap<String, TyConId>,
) -> (Vec<DerivedInstance>, Vec<TypeError>) {
    let mut generated: Vec<DerivedInstance> = Vec::new();
    let mut errors: Vec<TypeError> = Vec::new();

    for class_ident in &type_decl.deriving {
        let class_name = &class_ident.text;
        let span = class_ident.span;

        // Reject unknown class.
        let Some(class_id) = class_table.id_by_name(class_name) else {
            errors.push(TypeError::NoInstance {
                class: class_name.clone(),
                ty: type_decl.name.text.clone(),
                span,
                fix_hint: format!("class `{class_name}` is not defined; check the class name"),
            });
            continue;
        };

        // Reject non-derivable class (only Eq, ToText/Show, Ord in 0.2.13).
        if !is_derivable(class_id) {
            errors.push(TypeError::NoInstance {
                class: class_name.clone(),
                ty: type_decl.name.text.clone(),
                span,
                fix_hint: format!(
                    "class `{class_name}` is not derivable in 0.2.13; \
                     only `Eq`, `ToText` (alias `Show`), and `Ord` support `deriving`"
                ),
            });
            continue;
        }

        // Generate method body and ctx_constraints for this class.
        match generate_body(
            class_id,
            &type_decl.body,
            &type_decl.name,
            span,
            user_tycon_names,
        ) {
            Err(e) => errors.push(e),
            Ok((body, ctx_constraints)) => {
                let method_name = method_name_for(class_id);
                let info = InstanceInfo {
                    def_module: Some(module_id),
                    methods: vec![(method_name.to_string(), String::new())],
                    ctx_constraints,
                    origin: InstanceOrigin::Explicit,
                    span,
                };
                let key = (class_id, tycon_id);
                let type_name = type_decl.name.text.clone();

                match instance_env.insert(key, info.clone(), class_name, &type_name) {
                    Ok(()) => {
                        generated.push(DerivedInstance {
                            key,
                            instance_info: info,
                            method_body: body,
                        });
                    }
                    Err(coherence_err) => {
                        errors.push(coherence_err.into_type_error());
                    }
                }
            }
        }
    }

    (generated, errors)
}

// ── Per-class generators ──────────────────────────────────────────────────────

/// Returns `true` if `class_id` is in the 0.2.13 derivable set
/// (`Eq`, `ToText`, `Ord`).
fn is_derivable(class_id: ridge_types::ClassId) -> bool {
    class_id == EQ_CLASS || class_id == TOTEXT_CLASS || class_id == ORD_CLASS
}

/// Returns the single method name for a derivable class.
fn method_name_for(class_id: ridge_types::ClassId) -> &'static str {
    if class_id == EQ_CLASS {
        "eq"
    } else if class_id == TOTEXT_CLASS {
        "toText"
    } else {
        // ORD_CLASS
        "compare"
    }
}

/// Generate the [`DerivedMethodBody`] and `ctx_constraints` for one class
/// applied to one type body.
///
/// Returns `Err(TypeError)` when the class cannot be derived for this type
/// (e.g. `Float` field in `Eq`).
fn generate_body(
    class_id: ridge_types::ClassId,
    body: &TypeBody,
    type_name: &Ident,
    span: Span,
    user_tycon_names: &FxHashMap<String, TyConId>,
) -> Result<(DerivedMethodBody, Vec<Constraint>), TypeError> {
    if class_id == EQ_CLASS {
        generate_eq(body, type_name, span, user_tycon_names)
    } else if class_id == TOTEXT_CLASS {
        Ok(generate_to_text(body))
    } else {
        // ORD_CLASS
        Ok(generate_ord(body))
    }
}

// ── derive Eq ─────────────────────────────────────────────────────────────────

/// Generate `derive Eq` — whole-value BEAM `=:=`.
///
/// Fails with T029 when any field type is `Float` (the float-footgun guard).
fn generate_eq(
    body: &TypeBody,
    type_name: &Ident,
    span: Span,
    user_tycon_names: &FxHashMap<String, TyConId>,
) -> Result<(DerivedMethodBody, Vec<Constraint>), TypeError> {
    // Walk all field types and reject `Float`.
    if let Some(float_field) = find_float_field(body, user_tycon_names) {
        return Err(TypeError::NoInstance {
            class: "Eq".to_string(),
            ty: type_name.text.clone(),
            span,
            fix_hint: format!(
                "floating-point equality is a footgun; `Eq Float` is intentionally \
                 omitted from the prelude. Field `{float_field}` has type `Float`. \
                 Do not derive `Eq` on `Float`-bearing types if equality must be \
                 correct. Use explicit comparison logic or `Crypto.constantTimeEq` \
                 for secrets."
            ),
        });
    }

    // Records (Erlang maps) and unions (tagged tuples / bare atoms) both lower
    // to BEAM values for which `=:=` gives the correct structural equality.
    // No ctx_constraints are needed: `=:=` is monomorphic in BEAM.
    Ok((DerivedMethodBody::DerivedEq, vec![]))
}

/// Walks the type body and returns the name of the first `Float`-typed field,
/// or `None` if no `Float` field is found.
///
/// Checks positional constructor args and record fields. Does not recurse
/// into nested types (a `List Float` field does not trigger this guard — the
/// float is wrapped in a container and the Eq instance for `List` already
/// handles structural equality correctly at the BEAM level).
fn find_float_field<'a>(
    body: &'a TypeBody,
    user_tycon_names: &FxHashMap<String, TyConId>,
) -> Option<&'a str> {
    match body {
        TypeBody::Record(r) => {
            for field in &r.fields {
                if ast_type_is_float(&field.ty, user_tycon_names) {
                    return Some(&field.name.text);
                }
            }
            None
        }
        TypeBody::Union(u) => {
            for ctor in &u.alternatives {
                match ctor {
                    Constructor::Positional { args, .. } => {
                        for ty in args {
                            if ast_type_is_float(ty, user_tycon_names) {
                                // Return a synthetic name for the positional payload.
                                return Some("(payload)");
                            }
                        }
                    }
                    Constructor::Record { body, .. } => {
                        for field in &body.fields {
                            if ast_type_is_float(&field.ty, user_tycon_names) {
                                return Some(&field.name.text);
                            }
                        }
                    }
                }
            }
            None
        }
        TypeBody::Alias(ty) => {
            if ast_type_is_float(ty, user_tycon_names) {
                Some("(alias)")
            } else {
                None
            }
        }
    }
}

/// Returns `true` if the AST type is `Float` (either as a primitive or a named
/// type that resolves to the Float `TyConId`).
fn ast_type_is_float(ty: &AstType, user_tycon_names: &FxHashMap<String, TyConId>) -> bool {
    use ridge_ast::base::PrimitiveType;
    match ty {
        AstType::Primitive {
            name: PrimitiveType::Float,
            ..
        } => true,
        AstType::Named { name, .. } => {
            // Resolve via user tycon names; Float is also in the builtin table.
            let id = user_tycon_names
                .get(name.text.as_str())
                .copied()
                .or_else(|| builtin_name_to_tycon_id(&name.text));
            id == Some(TyConId(1)) // Float = TyConId(1)
        }
        _ => false,
    }
}

// ── derive ToText ─────────────────────────────────────────────────────────────

/// Generate `derive ToText`.
///
/// - Records → `"TypeName { f1 = " ++ toText(f1) ++ ", f2 = " ++ toText(f2) ++ " }"`.
///   Each field requires a `ToText` instance for its type; `field_tycons` carries
///   the resolved `TyConId` per field so the lowering pass can select the right
///   stdlib dispatch (e.g. `std.int.toText` for `Int`).
/// - Unions → `"CtorName"` for nullary constructors; `"CtorName(f1, f2)"` with
///   per-payload `toText` dispatch for payload constructors.
fn generate_to_text(body: &TypeBody) -> (DerivedMethodBody, Vec<Constraint>) {
    // ctx_constraints: in 0.2.13 all fields of derivable user types are concrete,
    // so the constraint is resolved statically at derive-registration time.
    // We leave ctx_constraints empty — the solver verifies at call sites using
    // the InstanceEnv. The structural synthesis only needs field names + TyConIds.
    match body {
        TypeBody::Record(r) => {
            let field_names: Vec<String> = r.fields.iter().map(|f| f.name.text.clone()).collect();
            let field_tycons: Vec<Option<TyConId>> = r
                .fields
                .iter()
                .map(|f| resolve_ast_type_to_tycon_id(&f.ty, &rustc_hash::FxHashMap::default()))
                .collect();
            (
                DerivedMethodBody::DerivedToTextRecord {
                    field_names,
                    field_tycons,
                },
                vec![],
            )
        }
        TypeBody::Union(u) => {
            let variants = u
                .alternatives
                .iter()
                .map(|ctor| match ctor {
                    Constructor::Positional { name, args, .. } => {
                        let tycons: Vec<Option<TyConId>> = args
                            .iter()
                            .map(|ty| {
                                resolve_ast_type_to_tycon_id(ty, &rustc_hash::FxHashMap::default())
                            })
                            .collect();
                        (name.text.clone(), args.len(), tycons)
                    }
                    Constructor::Record { name, body, .. } => {
                        let tycons: Vec<Option<TyConId>> = body
                            .fields
                            .iter()
                            .map(|f| {
                                resolve_ast_type_to_tycon_id(
                                    &f.ty,
                                    &rustc_hash::FxHashMap::default(),
                                )
                            })
                            .collect();
                        (name.text.clone(), body.fields.len(), tycons)
                    }
                })
                .collect();
            (DerivedMethodBody::DerivedToTextUnion { variants }, vec![])
        }
        TypeBody::Alias(_) => {
            // Alias types are structural wrappers; the ToText of the underlying
            // type is correct, but we cannot derive it without knowing the
            // underlying type's class instance at this point. For 0.2.13 this
            // case is uncommon; represent it as a zero-field record render.
            (
                DerivedMethodBody::DerivedToTextRecord {
                    field_names: vec![],
                    field_tycons: vec![],
                },
                vec![],
            )
        }
    }
}

// ── derive Ord ────────────────────────────────────────────────────────────────

/// Generate `derive Ord`.
///
/// - Records → field-by-field in declared order, first non-`Equal` wins.
///   Requires `Ord` per field type (`ctx_constraints`).
/// - Unions → compare variant index first; if same variant and has payload,
///   compare payload fields in order. Requires `Ord` per payload type.
///
/// Returns `Ordering` (`Less | Equal | Greater`). The `Eq` superclass
/// requirement is checked by coherence (T033) — not validated here.
fn generate_ord(body: &TypeBody) -> (DerivedMethodBody, Vec<Constraint>) {
    match body {
        TypeBody::Record(r) => {
            let field_names = r.fields.iter().map(|f| f.name.text.clone()).collect();
            (DerivedMethodBody::DerivedOrdRecord { field_names }, vec![])
        }
        TypeBody::Union(u) => {
            let variants = u
                .alternatives
                .iter()
                .map(|ctor| match ctor {
                    Constructor::Positional { name, args, .. } => (name.text.clone(), args.len()),
                    Constructor::Record { name, body, .. } => {
                        (name.text.clone(), body.fields.len())
                    }
                })
                .collect();
            (DerivedMethodBody::DerivedOrdUnion { variants }, vec![])
        }
        TypeBody::Alias(_) => {
            // Delegate to the underlying type's Ord.
            (
                DerivedMethodBody::DerivedOrdRecord {
                    field_names: vec![],
                },
                vec![],
            )
        }
    }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/// Maps a builtin type name to its fixed `TyConId` (mirrors the assignment in
/// `BuiltinTyCons::allocate`). Returns `None` for user-defined or unknown types.
fn builtin_name_to_tycon_id(name: &str) -> Option<TyConId> {
    match name {
        "Int" => Some(TyConId(0)),
        "Float" => Some(TyConId(1)),
        "Bool" => Some(TyConId(2)),
        "Text" => Some(TyConId(3)),
        "Unit" => Some(TyConId(4)),
        "Timestamp" => Some(TyConId(5)),
        "List" => Some(TyConId(6)),
        "Map" => Some(TyConId(7)),
        "Set" => Some(TyConId(8)),
        "Option" => Some(TyConId(9)),
        "Result" => Some(TyConId(10)),
        "Handle" => Some(TyConId(11)),
        "Error" => Some(TyConId(12)),
        "Duration" => Some(TyConId(13)),
        "ProcOutput" => Some(TyConId(14)),
        "Ordering" => Some(TyConId(15)),
        _ => None,
    }
}

/// Collects all concrete field/payload types from a type body as `TyConId`s.
///
/// Used internally to enumerate `ctx_constraint` candidates. Returns only types
/// that can be resolved to a known `TyConId`.
#[allow(dead_code)]
fn collect_field_tycon_ids(
    body: &TypeBody,
    user_tycon_names: &FxHashMap<String, TyConId>,
) -> Vec<TyConId> {
    let mut ids = Vec::new();
    let fields: Vec<&AstType> = match body {
        TypeBody::Record(r) => r.fields.iter().map(|f: &FieldDecl| &f.ty).collect(),
        TypeBody::Union(u) => u
            .alternatives
            .iter()
            .flat_map(|ctor| match ctor {
                Constructor::Positional { args, .. } => args.iter().collect::<Vec<_>>(),
                Constructor::Record { body, .. } => body.fields.iter().map(|f| &f.ty).collect(),
            })
            .collect(),
        TypeBody::Alias(ty) => vec![ty],
    };

    for ty in fields {
        if let Some(id) = resolve_ast_type_to_tycon_id(ty, user_tycon_names) {
            ids.push(id);
        }
    }
    ids
}

/// Resolves an AST type to a `TyConId` if the type is a simple named or
/// primitive type. Returns `None` for parametric types, function types, etc.
fn resolve_ast_type_to_tycon_id(
    ty: &AstType,
    user_tycon_names: &FxHashMap<String, TyConId>,
) -> Option<TyConId> {
    use ridge_ast::base::PrimitiveType;
    match ty {
        AstType::Primitive { name, .. } => match name {
            PrimitiveType::Int => Some(TyConId(0)),
            PrimitiveType::Float => Some(TyConId(1)),
            PrimitiveType::Bool => Some(TyConId(2)),
            PrimitiveType::Text => Some(TyConId(3)),
            PrimitiveType::Unit => Some(TyConId(4)),
            PrimitiveType::Timestamp => Some(TyConId(5)),
            #[allow(unreachable_patterns)]
            _ => None,
        },
        AstType::Named { name, .. } => user_tycon_names
            .get(name.text.as_str())
            .copied()
            .or_else(|| builtin_name_to_tycon_id(&name.text)),
        _ => None,
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use ridge_ast::{
        decl::{FieldDecl, RecordTypeBody, TypeBody, UnionTypeBody},
        Ident, Span, Type as AstType,
    };
    use ridge_types::{EQ_CLASS, ORD_CLASS, TOTEXT_CLASS};

    use crate::class_env::{
        register_prelude_classes, register_prelude_instances, ClassTable, InstanceEnv,
    };

    fn ds() -> Span {
        Span::point(0)
    }

    fn ident(s: &str) -> Ident {
        Ident {
            text: s.to_string(),
            span: ds(),
        }
    }

    fn int_type() -> AstType {
        use ridge_ast::base::PrimitiveType;
        AstType::Primitive {
            name: PrimitiveType::Int,
            span: ds(),
        }
    }

    fn float_type() -> AstType {
        use ridge_ast::base::PrimitiveType;
        AstType::Primitive {
            name: PrimitiveType::Float,
            span: ds(),
        }
    }

    fn make_class_table() -> ClassTable {
        let mut ct = ClassTable::new();
        register_prelude_classes(&mut ct);
        ct
    }

    fn make_instance_env() -> InstanceEnv {
        let mut env = InstanceEnv::new();
        register_prelude_instances(&mut env);
        env
    }

    fn record_body(fields: Vec<(&str, AstType)>) -> TypeBody {
        TypeBody::Record(RecordTypeBody {
            fields: fields
                .into_iter()
                .map(|(name, ty)| FieldDecl {
                    name: ident(name),
                    ty,
                    span: ds(),
                })
                .collect(),
            span: ds(),
        })
    }

    fn union_body(variants: Vec<(&str, Vec<AstType>)>) -> TypeBody {
        TypeBody::Union(UnionTypeBody {
            alternatives: variants
                .into_iter()
                .map(|(name, args)| ridge_ast::decl::Constructor::Positional {
                    name: ident(name),
                    args,
                    span: ds(),
                })
                .collect(),
            span: ds(),
        })
    }

    fn type_decl_with_body(
        name: &str,
        body: TypeBody,
        deriving: Vec<&str>,
    ) -> ridge_ast::decl::TypeDecl {
        use ridge_ast::decl::TypeDecl;
        use ridge_ast::Visibility;
        TypeDecl {
            vis: Visibility::Private,
            name: ident(name),
            params: vec![],
            body,
            deriving: deriving.into_iter().map(ident).collect(),
            span: ds(),
            doc: None,
        }
    }

    // ── derive Eq on a record ────────────────────────────────────────────────

    #[test]
    fn derive_eq_record_no_float_succeeds() {
        let ct = make_class_table();
        let mut env = make_instance_env();
        // Point = { x: Int, y: Int }
        let decl = type_decl_with_body(
            "Point",
            record_body(vec![("x", int_type()), ("y", int_type())]),
            vec!["Eq"],
        );
        let (generated, errors) = derive_instances(
            &decl,
            TyConId(100),
            42,
            &ct,
            &mut env,
            &FxHashMap::default(),
        );
        assert!(errors.is_empty(), "no errors expected: {errors:?}");
        assert_eq!(generated.len(), 1, "one instance generated");
        assert!(matches!(
            generated[0].method_body,
            DerivedMethodBody::DerivedEq
        ));
        // Instance must be registered.
        assert!(
            env.get((EQ_CLASS, TyConId(100))).is_some(),
            "Eq instance must be in InstanceEnv"
        );
    }

    // ── derive Eq on a union ─────────────────────────────────────────────────

    #[test]
    fn derive_eq_union_no_float_succeeds() {
        let ct = make_class_table();
        let mut env = make_instance_env();
        // Color = Red | Green | Blue
        let decl = type_decl_with_body(
            "Color",
            union_body(vec![("Red", vec![]), ("Green", vec![]), ("Blue", vec![])]),
            vec!["Eq"],
        );
        let (generated, errors) =
            derive_instances(&decl, TyConId(17), 42, &ct, &mut env, &FxHashMap::default());
        assert!(errors.is_empty(), "no errors: {errors:?}");
        assert_eq!(generated.len(), 1);
        assert!(matches!(
            generated[0].method_body,
            DerivedMethodBody::DerivedEq
        ));
    }

    // ── derive Eq on a Float-bearing record → T029 ───────────────────────────

    #[test]
    fn derive_eq_float_field_emits_t029() {
        let ct = make_class_table();
        let mut env = make_instance_env();
        // BadPoint = { x: Float, y: Float }
        let decl = type_decl_with_body(
            "BadPoint",
            record_body(vec![("x", float_type()), ("y", float_type())]),
            vec!["Eq"],
        );
        let (generated, errors) =
            derive_instances(&decl, TyConId(18), 42, &ct, &mut env, &FxHashMap::default());
        assert!(generated.is_empty(), "no instance should be generated");
        assert_eq!(errors.len(), 1, "one T029 expected");
        assert_eq!(
            errors[0].code(),
            "T029",
            "float Eq guard must emit T029: {errors:?}"
        );
        // The hint must mention the float footgun.
        let rendered = format!("{errors:?}");
        assert!(
            rendered.contains("footgun")
                || rendered.contains("float")
                || rendered.contains("Float"),
            "T029 hint must mention float footgun: {rendered}"
        );
    }

    // ── derive ToText on a record ─────────────────────────────────────────────

    #[test]
    fn derive_to_text_record_succeeds() {
        let ct = make_class_table();
        let mut env = make_instance_env();
        let decl = type_decl_with_body(
            "Point",
            record_body(vec![("x", int_type()), ("y", int_type())]),
            vec!["ToText"],
        );
        let (generated, errors) =
            derive_instances(&decl, TyConId(19), 42, &ct, &mut env, &FxHashMap::default());
        assert!(errors.is_empty(), "no errors: {errors:?}");
        assert_eq!(generated.len(), 1);
        if let DerivedMethodBody::DerivedToTextRecord {
            field_names,
            field_tycons,
        } = &generated[0].method_body
        {
            assert_eq!(
                field_names,
                &["x", "y"],
                "expected field names [x, y], got {field_names:?}"
            );
            // Int fields resolve to TyConId(0).
            assert_eq!(
                field_tycons,
                &[Some(TyConId(0)), Some(TyConId(0))],
                "Int fields must resolve to TyConId(0): {field_tycons:?}"
            );
        } else {
            panic!(
                "expected DerivedToTextRecord with field names [x, y], got {:?}",
                generated[0].method_body
            );
        }
        assert!(env.get((TOTEXT_CLASS, TyConId(19))).is_some());
    }

    // ── derive ToText on a union ──────────────────────────────────────────────

    #[test]
    fn derive_to_text_union_succeeds() {
        let ct = make_class_table();
        let mut env = make_instance_env();
        // Color = Red | Green | Blue (all nullary)
        let decl = type_decl_with_body(
            "Color",
            union_body(vec![("Red", vec![]), ("Green", vec![]), ("Blue", vec![])]),
            vec!["ToText"],
        );
        let (generated, errors) =
            derive_instances(&decl, TyConId(20), 42, &ct, &mut env, &FxHashMap::default());
        assert!(errors.is_empty(), "no errors: {errors:?}");
        assert_eq!(generated.len(), 1);
        if let DerivedMethodBody::DerivedToTextUnion { variants } = &generated[0].method_body {
            // Nullary variants: 3-tuple (name, 0, []) — no payload TyConIds.
            assert_eq!(variants.len(), 3, "Color has 3 variants");
            assert_eq!(variants[0].0, "Red");
            assert_eq!(variants[0].1, 0);
            assert!(variants[0].2.is_empty());
            assert_eq!(variants[1].0, "Green");
            assert_eq!(variants[2].0, "Blue");
        } else {
            panic!(
                "expected DerivedToTextUnion, got {:?}",
                generated[0].method_body
            );
        }
    }

    // ── derive Ord on a union ─────────────────────────────────────────────────

    #[test]
    fn derive_ord_union_variant_ordering() {
        let ct = make_class_table();
        let mut env = make_instance_env();
        // Color = Red | Green | Blue; also derive Eq (Ord superclass)
        let decl = type_decl_with_body(
            "Color",
            union_body(vec![("Red", vec![]), ("Green", vec![]), ("Blue", vec![])]),
            vec!["Eq", "Ord"],
        );
        let (generated, errors) =
            derive_instances(&decl, TyConId(21), 42, &ct, &mut env, &FxHashMap::default());
        assert!(errors.is_empty(), "no errors: {errors:?}");
        // Two instances: Eq and Ord.
        assert_eq!(generated.len(), 2, "expected 2 instances (Eq + Ord)");
        let ord_inst = generated
            .iter()
            .find(|g| g.key.0 == ORD_CLASS)
            .expect("Ord instance must be generated");
        if let DerivedMethodBody::DerivedOrdUnion { variants } = &ord_inst.method_body {
            assert_eq!(variants.len(), 3, "Color has 3 variants");
            assert_eq!(variants[0].0, "Red");
            assert_eq!(variants[1].0, "Green");
            assert_eq!(variants[2].0, "Blue");
        } else {
            panic!("expected DerivedOrdUnion, got {:?}", ord_inst.method_body);
        }
    }

    // ── derive Ord on a record ────────────────────────────────────────────────

    #[test]
    fn derive_ord_record_field_order() {
        let ct = make_class_table();
        let mut env = make_instance_env();
        let decl = type_decl_with_body(
            "Point",
            record_body(vec![("x", int_type()), ("y", int_type())]),
            vec!["Eq", "Ord"],
        );
        let (generated, errors) =
            derive_instances(&decl, TyConId(22), 42, &ct, &mut env, &FxHashMap::default());
        assert!(errors.is_empty(), "no errors: {errors:?}");
        let ord = generated
            .iter()
            .find(|g| g.key.0 == ORD_CLASS)
            .expect("Ord instance");
        if let DerivedMethodBody::DerivedOrdRecord { field_names } = &ord.method_body {
            assert_eq!(field_names, &["x", "y"]);
        } else {
            panic!("expected DerivedOrdRecord, got {:?}", ord.method_body);
        }
    }

    // ── T032 — derive conflicts with explicit instance ────────────────────────

    #[test]
    fn derive_after_explicit_instance_t032() {
        use crate::class_env::{InstanceInfo, InstanceOrigin};

        let ct = make_class_table();
        let mut env = make_instance_env();

        // Pre-insert an explicit Eq instance for TyConId(23).
        env.insert(
            (EQ_CLASS, TyConId(23)),
            InstanceInfo {
                def_module: Some(0),
                methods: vec![("eq".to_string(), String::new())],
                ctx_constraints: vec![],
                origin: InstanceOrigin::Explicit,
                span: ds(),
            },
            "Eq",
            "Foo",
        )
        .expect("explicit insert ok");

        // Now try to derive Eq for the same type — should produce T032.
        let decl = type_decl_with_body("Foo", union_body(vec![("A", vec![])]), vec!["Eq"]);
        let (generated, errors) =
            derive_instances(&decl, TyConId(23), 42, &ct, &mut env, &FxHashMap::default());
        assert!(generated.is_empty(), "no instance generated on conflict");
        assert!(
            errors.iter().any(|e| e.code() == "T032"),
            "duplicate derive + explicit must emit T032: {errors:?}"
        );
    }

    // ── Unknown class → error ─────────────────────────────────────────────────

    #[test]
    fn derive_unknown_class_emits_error() {
        let ct = make_class_table();
        let mut env = make_instance_env();
        let decl = type_decl_with_body(
            "Foo",
            union_body(vec![("A", vec![])]),
            vec!["Serializable"], // not a known class
        );
        let (generated, errors) =
            derive_instances(&decl, TyConId(24), 42, &ct, &mut env, &FxHashMap::default());
        assert!(generated.is_empty());
        assert_eq!(errors.len(), 1);
        assert_eq!(errors[0].code(), "T029", "unknown class → T029");
    }

    // ── Non-derivable class → error ───────────────────────────────────────────

    #[test]
    fn derive_non_derivable_class_emits_error() {
        let mut ct = make_class_table();
        let mut env = make_instance_env();
        // Register a real user class that is not in the derivable set.
        let _ = ct.intern("Fancy");
        let decl = type_decl_with_body("Foo", union_body(vec![("A", vec![])]), vec!["Fancy"]);
        let (generated, errors) =
            derive_instances(&decl, TyConId(25), 42, &ct, &mut env, &FxHashMap::default());
        assert!(generated.is_empty());
        assert_eq!(errors.len(), 1);
        assert_eq!(errors[0].code(), "T029");
    }

    // ── Prelude instances present in env ──────────────────────────────────────

    #[test]
    fn prelude_eq_int_registered() {
        let env = make_instance_env();
        assert!(
            env.get((EQ_CLASS, TyConId(0))).is_some(),
            "Eq Int must be in the prelude instance env"
        );
    }

    #[test]
    fn prelude_eq_float_absent() {
        let env = make_instance_env();
        assert!(
            env.get((EQ_CLASS, TyConId(1))).is_none(),
            "Eq Float must NOT be in the prelude instance env"
        );
    }

    #[test]
    fn prelude_totext_float_registered() {
        let env = make_instance_env();
        assert!(
            env.get((TOTEXT_CLASS, TyConId(1))).is_some(),
            "ToText Float must be in the prelude instance env"
        );
    }

    #[test]
    fn prelude_ord_int_registered() {
        let env = make_instance_env();
        assert!(
            env.get((ORD_CLASS, TyConId(0))).is_some(),
            "Ord Int must be in the prelude instance env"
        );
    }

    #[test]
    fn prelude_eq_ordering_registered() {
        let env = make_instance_env();
        assert!(
            env.get((EQ_CLASS, TyConId(15))).is_some(),
            "Eq Ordering must be registered (required as Ord Ordering's superclass)"
        );
    }

    // ── build_fix_hint Float guard in solve.rs is correct ────────────────────
    // (Verify from the derive side that Float = TyConId(1), not TyConId(4).)

    #[test]
    fn float_is_tycon_id_1_not_4() {
        // Confirm that a Float AST type resolves to TyConId(1).
        use ridge_ast::base::PrimitiveType;
        let float_ty = AstType::Primitive {
            name: PrimitiveType::Float,
            span: Span::point(0),
        };
        assert!(
            ast_type_is_float(&float_ty, &FxHashMap::default()),
            "Float primitive must be recognised as Float"
        );
        // TyConId(4) is Unit, not Float.
        let unit_ty = AstType::Primitive {
            name: PrimitiveType::Unit,
            span: Span::point(0),
        };
        assert!(
            !ast_type_is_float(&unit_ty, &FxHashMap::default()),
            "Unit must NOT be recognised as Float"
        );
    }
}
