// @generated by crates/ridge-typecheck/build.rs (T10).
// Source of truth: crates/ridge-typecheck/src/stdlib_signatures_impl.rs
// Do not edit this OUT_DIR copy by hand — re-run cargo build to regenerate.
//
// Stdlib signature table: maps `(StdlibModuleId, symbol-name) -> Scheme`.
//
// # Phase 4 contract
//
// This file is hand-curated for Phase 4 (≈ 163 entries across 18 modules).
// It will be replaced with a generated table derived from the actual stdlib
// source.
//
// # Capability variables (D041, D057)
//
// Only stdlib HOFs that accept a callback may carry `CapRow::Var(CapVid)`.
// User-written functions never introduce `CapVids`; instantiation in T6
// replaces them with fresh `CapVids` at each call site.
//
// # Stubs
//
// Entries annotated `// TODO: hand-curated stub` return a
// monomorphic `Scheme { vars: vec![], cap_vars: vec![], ty: Type::Error }`.
// The property test checks that every BUILTINS export resolves to `Some(Scheme)`.

use ridge_resolve::StdlibModuleId;
use ridge_types::{CapRow, CapVid, CapabilitySet, Scheme, TyVid, Type};

#[cfg(test)]
use ridge_resolve::BUILTINS;

use crate::BuiltinTyCons;

// ── StdlibModuleId constants ──────────────────────────────────────────────────
//
// These mirror BUILTINS[i].id in stdlib_builtin.rs.

const STD_INT: StdlibModuleId = StdlibModuleId(0);
const STD_FLOAT: StdlibModuleId = StdlibModuleId(1);
const STD_BOOL: StdlibModuleId = StdlibModuleId(2);
const STD_TEXT: StdlibModuleId = StdlibModuleId(3);
const STD_LIST: StdlibModuleId = StdlibModuleId(4);
const STD_MAP: StdlibModuleId = StdlibModuleId(5);
const STD_SET: StdlibModuleId = StdlibModuleId(6);
const STD_OPTION: StdlibModuleId = StdlibModuleId(7);
const STD_RESULT: StdlibModuleId = StdlibModuleId(8);
const STD_IO: StdlibModuleId = StdlibModuleId(9);
const STD_FS: StdlibModuleId = StdlibModuleId(10);
const STD_TIME: StdlibModuleId = StdlibModuleId(11);
const STD_RANDOM: StdlibModuleId = StdlibModuleId(12);
const STD_ENV: StdlibModuleId = StdlibModuleId(13);
const STD_CLI: StdlibModuleId = StdlibModuleId(14);
const STD_PROC: StdlibModuleId = StdlibModuleId(15);
const STD_ACTOR: StdlibModuleId = StdlibModuleId(16);
const STD_JSON: StdlibModuleId = StdlibModuleId(17);
const STD_NET_HTTP: StdlibModuleId = StdlibModuleId(18);
const STD_CRYPTO: StdlibModuleId = StdlibModuleId(19);
// std.sql is module 20; its codec schemes (SqlType/SqlValue) are seeded
// separately, but the plain `sql`/`sqlValue` helpers are hand-curated below.
const STD_SQL: StdlibModuleId = StdlibModuleId(20);
// std.schema (id 21) is fully reconciled — its schemes come from
// `reconciled_ctor_scheme` / `reconciled_fn_scheme`, so it has no constant here.
const STD_QUERY: StdlibModuleId = StdlibModuleId(22);
// std.data (23), std.repo (24), std.migrate (25), std.raw (26) are reconciled —
// their schemes come from `reconciled_fn_scheme`, so they have no constant here.
const STD_TEST: StdlibModuleId = StdlibModuleId(27);
// std.decimal is interned last (id 28) so it takes the highest id without
// renumbering the modules ahead of it.
const STD_DECIMAL: StdlibModuleId = StdlibModuleId(28);

// ── Type-building helpers ─────────────────────────────────────────────────────
//
// These produce monomorphic Type nodes. Helpers keep match arms readable.

#[inline]
const fn ty_int(b: &BuiltinTyCons) -> Type {
    Type::Con(b.int, vec![])
}
#[inline]
const fn ty_float(b: &BuiltinTyCons) -> Type {
    Type::Con(b.float, vec![])
}
#[inline]
const fn ty_bool(b: &BuiltinTyCons) -> Type {
    Type::Con(b.bool, vec![])
}
#[inline]
const fn ty_text(b: &BuiltinTyCons) -> Type {
    Type::Con(b.text, vec![])
}
#[inline]
const fn ty_unit(b: &BuiltinTyCons) -> Type {
    Type::Con(b.unit, vec![])
}
#[inline]
const fn ty_timestamp(b: &BuiltinTyCons) -> Type {
    Type::Con(b.timestamp, vec![])
}
#[inline]
const fn ty_decimal(b: &BuiltinTyCons) -> Type {
    Type::Con(b.decimal, vec![])
}
#[inline]
const fn ty_error(b: &BuiltinTyCons) -> Type {
    Type::Con(b.error, vec![])
}
#[inline]
const fn ty_duration(b: &BuiltinTyCons) -> Type {
    Type::Con(b.duration, vec![])
}
#[inline]
const fn ty_proc_output(b: &BuiltinTyCons) -> Type {
    Type::Con(b.proc_output, vec![])
}
#[inline]
const fn ty_json_value(b: &BuiltinTyCons) -> Type {
    Type::Con(b.json_value, vec![])
}
#[inline]
fn ty_list(b: &BuiltinTyCons, elem: Type) -> Type {
    Type::Con(b.list, vec![elem])
}
#[inline]
fn ty_map(b: &BuiltinTyCons, k: Type, v: Type) -> Type {
    Type::Con(b.map, vec![k, v])
}
#[inline]
fn ty_set(b: &BuiltinTyCons, a: Type) -> Type {
    Type::Con(b.set, vec![a])
}
#[inline]
fn ty_option(b: &BuiltinTyCons, a: Type) -> Type {
    Type::Con(b.option, vec![a])
}
#[inline]
fn ty_handle(b: &BuiltinTyCons, a: Type) -> Type {
    Type::Con(b.handle, vec![a])
}
#[inline]
fn ty_result(b: &BuiltinTyCons, ok: Type, err: Type) -> Type {
    Type::Con(b.result, vec![ok, err])
}
/// Monomorphic function type with an empty (pure) capability set.
#[inline]
fn ty_fn_pure(params: Vec<Type>, ret: Type) -> Type {
    Type::Fn {
        params,
        ret: Box::new(ret),
        caps: CapRow::Concrete(CapabilitySet::PURE),
    }
}
/// Monomorphic function type with a concrete capability set.
#[inline]
fn ty_fn_caps(params: Vec<Type>, ret: Type, caps: CapabilitySet) -> Type {
    Type::Fn {
        params,
        ret: Box::new(ret),
        caps: CapRow::Concrete(caps),
    }
}
/// Capability-polymorphic function type: the callback argument uses `CapRow::Var(c)`.
/// The outer function re-uses the same `CapVid` so the call site absorbs whatever
/// capability the user-supplied callback requires (D041).
#[inline]
fn ty_fn_cap_var(params: Vec<Type>, ret: Type, c: CapVid) -> Type {
    Type::Fn {
        params,
        ret: Box::new(ret),
        caps: CapRow::Var(c),
    }
}

/// Builds a polymorphic `Scheme` with no cap vars.
#[inline]
const fn poly(vars: Vec<TyVid>, ty: Type) -> Scheme {
    Scheme {
        vars,
        cap_vars: vec![],
        row_vars: vec![],
        ty,
        constraints: vec![],
    }
}

/// Builds a polymorphic `Scheme` with cap vars (for HOFs).
#[inline]
const fn poly_cap(vars: Vec<TyVid>, cap_vars: Vec<CapVid>, ty: Type) -> Scheme {
    Scheme {
        vars,
        cap_vars,
        row_vars: vec![],
        ty,
        constraints: vec![],
    }
}

/// Builds a monomorphic scheme.
#[inline]
const fn mono(ty: Type) -> Scheme {
    Scheme {
        vars: vec![],
        cap_vars: vec![],
        row_vars: vec![],
        ty,
        constraints: vec![],
    }
}

/// Stub: returns `Type::Error` wrapped in a monomorphic scheme.
///
/// Used for entries whose exact signature is pending auto-generation.
/// The property test checks every BUILTINS export resolves to
/// `Some(Scheme)`, so stubs return `Some` (not `None`).
#[inline]
#[expect(
    clippy::unnecessary_wraps,
    reason = "uniform Option<Scheme> signature for caller compatibility"
)]
const fn stub_phase7() -> Option<Scheme> {
    // TODO: hand-curated stub — replace with generated table.
    Some(mono(Type::Error))
}

// ── Type variables ────────────────────────────────────────────────────────────
//
// Stable bound variable indices used in scheme bodies.
// These are never unification variables — they are generalized slots
// replaced by fresh TyVids at each call to `Scheme::instantiate` (T6).

const A: TyVid = TyVid(0);
const B_VAR: TyVid = TyVid(1);
const C_VAR: TyVid = TyVid(2);
const CAP_C: CapVid = CapVid(0);

// ── Main dispatch ─────────────────────────────────────────────────────────────

/// Returns the `Scheme` for a stdlib symbol, or `None` if the `(module, name)`
/// pair is unknown.
///
/// `b` provides stable `TyConId`s for the 12 built-in types (T3).
///
/// Every export listed in [`ridge_resolve::stdlib_builtin::BUILTINS`] is covered: entries either carry a
/// real `Scheme` or a `Type::Error` stub annotated `// TODO: hand-curated stub`.
#[must_use]
#[expect(clippy::too_many_lines, reason = "one match arm per stdlib symbol")]
pub fn stdlib_signature(module: StdlibModuleId, name: &str, b: &BuiltinTyCons) -> Option<Scheme> {
    match (module, name) {
        // ── std.int ───────────────────────────────────────────────────────────
        (STD_INT, "toText") => Some(mono(ty_fn_pure(vec![ty_int(b)], ty_text(b)))),
        (STD_INT, "parse") => Some(mono(ty_fn_pure(vec![ty_text(b)], ty_option(b, ty_int(b))))),
        // T12: abs, neg — unary Int -> Int.
        (STD_INT, "abs" | "neg") => Some(mono(ty_fn_pure(vec![ty_int(b)], ty_int(b)))),
        // T12: binary Int -> Int -> Int (min, max, add, sub, mul, div, rem, mod, wrappingAdd, saturatingAdd).
        (
            STD_INT,
            "min" | "max" | "add" | "sub" | "mul" | "div" | "rem" | "mod" | "pow"
            | "wrappingAdd" | "saturatingAdd",
        ) => Some(mono(ty_fn_pure(vec![ty_int(b), ty_int(b)], ty_int(b)))),

        // ── std.float ─────────────────────────────────────────────────────────
        (STD_FLOAT, "toText") => Some(mono(ty_fn_pure(vec![ty_float(b)], ty_text(b)))),
        (STD_FLOAT, "parse") => Some(mono(ty_fn_pure(
            vec![ty_text(b)],
            ty_option(b, ty_float(b)),
        ))),
        // T12: unary Float -> Int (round, floor, ceil, truncate).
        (STD_FLOAT, "round" | "floor" | "ceil" | "truncate") => {
            Some(mono(ty_fn_pure(vec![ty_float(b)], ty_int(b))))
        }
        // T12: unary Float -> Float (sqrt, abs, neg).
        (STD_FLOAT, "sqrt" | "abs" | "neg") => {
            Some(mono(ty_fn_pure(vec![ty_float(b)], ty_float(b))))
        }
        (STD_FLOAT, "fromInt") => Some(mono(ty_fn_pure(vec![ty_int(b)], ty_float(b)))),
        // T12: parseRaw — Text -> Float (no Option — may panic on bad input).
        (STD_FLOAT, "parseRaw") => Some(mono(ty_fn_pure(vec![ty_text(b)], ty_float(b)))),
        // T12: binary Float -> Float -> Float (add, sub, mul, div).
        (STD_FLOAT, "add" | "sub" | "mul" | "div") => {
            Some(mono(ty_fn_pure(vec![ty_float(b), ty_float(b)], ty_float(b))))
        }
        // totalCompare: Float -> Float -> Int  (returns -1 / 0 / 1)
        (STD_FLOAT, "totalCompare") => {
            Some(mono(ty_fn_pure(vec![ty_float(b), ty_float(b)], ty_int(b))))
        }

        // ── std.decimal ───────────────────────────────────────────────────────
        // fromText: Text -> Result Decimal Error
        (STD_DECIMAL, "fromText") => Some(mono(ty_fn_pure(
            vec![ty_text(b)],
            ty_result(b, ty_decimal(b), ty_error(b)),
        ))),
        (STD_DECIMAL, "toText") => Some(mono(ty_fn_pure(vec![ty_decimal(b)], ty_text(b)))),
        (STD_DECIMAL, "fromInt") => Some(mono(ty_fn_pure(vec![ty_int(b)], ty_decimal(b)))),
        (STD_DECIMAL, "parseRaw") => Some(mono(ty_fn_pure(vec![ty_text(b)], ty_decimal(b)))),
        (STD_DECIMAL, "toFloat") => Some(mono(ty_fn_pure(vec![ty_decimal(b)], ty_float(b)))),
        // Exact binary arithmetic: Decimal -> Decimal -> Decimal.
        (STD_DECIMAL, "add" | "sub" | "mul") => Some(mono(ty_fn_pure(
            vec![ty_decimal(b), ty_decimal(b)],
            ty_decimal(b),
        ))),
        // Unary arithmetic: Decimal -> Decimal.
        (STD_DECIMAL, "neg" | "abs") => {
            Some(mono(ty_fn_pure(vec![ty_decimal(b)], ty_decimal(b))))
        }
        // truncate: Int -> Decimal -> Decimal (round toward zero to a scale). It
        // names no reconciled type, so it lives in this table; `round`/`div`, which
        // take a RoundingMode, are seeded via reconciled_fn_scheme.
        (STD_DECIMAL, "truncate") => Some(mono(ty_fn_pure(
            vec![ty_int(b), ty_decimal(b)],
            ty_decimal(b),
        ))),
        // compare: Decimal -> Decimal -> Int (-1 / 0 / 1, value-based so 1.5 == 1.50).
        (STD_DECIMAL, "compare") => {
            Some(mono(ty_fn_pure(vec![ty_decimal(b), ty_decimal(b)], ty_int(b))))
        }
        // The value comparisons: Decimal -> Decimal -> Bool.
        (STD_DECIMAL, "eq" | "lt" | "lte" | "gt" | "gte") => {
            Some(mono(ty_fn_pure(vec![ty_decimal(b), ty_decimal(b)], ty_bool(b))))
        }

        // ── std.bool ──────────────────────────────────────────────────────────
        (STD_BOOL, "not") => Some(mono(ty_fn_pure(vec![ty_bool(b)], ty_bool(b)))),
        (STD_BOOL, "and" | "or") => {
            Some(mono(ty_fn_pure(vec![ty_bool(b), ty_bool(b)], ty_bool(b))))
        }
        // T12: toText present in bool.ridge.
        (STD_BOOL, "toText") => Some(mono(ty_fn_pure(vec![ty_bool(b)], ty_text(b)))),

        // ── std.text ──────────────────────────────────────────────────────────
        (STD_TEXT, "length" | "byteSize") => Some(mono(ty_fn_pure(vec![ty_text(b)], ty_int(b)))),
        (STD_TEXT, "concat") => Some(mono(ty_fn_pure(vec![ty_text(b), ty_text(b)], ty_text(b)))),
        (STD_TEXT, "join") => Some(mono(ty_fn_pure(
            vec![ty_text(b), ty_list(b, ty_text(b))],
            ty_text(b),
        ))),
        (STD_TEXT, "slice") => Some(mono(ty_fn_pure(
            vec![ty_int(b), ty_int(b), ty_text(b)],
            ty_text(b),
        ))),
        (STD_TEXT, "split" | "splitAny") => Some(mono(ty_fn_pure(
            vec![ty_text(b), ty_text(b)],
            ty_list(b, ty_text(b)),
        ))),
        (STD_TEXT, "splitN") => Some(mono(ty_fn_pure(
            vec![ty_text(b), ty_text(b), ty_int(b)],
            ty_list(b, ty_text(b)),
        ))),
        (STD_TEXT, "lines") => Some(mono(ty_fn_pure(vec![ty_text(b)], ty_list(b, ty_text(b))))),
        (STD_TEXT, "trim" | "toUpper" | "toLower") => {
            Some(mono(ty_fn_pure(vec![ty_text(b)], ty_text(b))))
        }
        (STD_TEXT, "startsWith" | "endsWith" | "contains" | "like") => {
            Some(mono(ty_fn_pure(vec![ty_text(b), ty_text(b)], ty_bool(b))))
        }
        (STD_TEXT, "replace") => Some(mono(ty_fn_pure(
            vec![ty_text(b), ty_text(b), ty_text(b)],
            ty_text(b),
        ))),
        // padLeft / padRight: width padChar text -> text (data-last convention)
        (STD_TEXT, "padLeft" | "padRight") => Some(mono(ty_fn_pure(
            vec![ty_int(b), ty_text(b), ty_text(b)],
            ty_text(b),
        ))),
        (STD_TEXT, "isEmpty") => Some(mono(ty_fn_pure(vec![ty_text(b)], ty_bool(b)))),

        // ── std.list ──────────────────────────────────────────────────────────
        //
        // HOFs (map, filter, filterMap, fold, foldRight, sortBy, groupBy,
        // flatMap, zipWith, find, any, all, forEach) use CapRow::Var(CAP_C)
        // on the callback so capability inference absorbs the user's callback
        // caps at the call site (D041).
        (STD_LIST, "empty") => {
            // forall a. List a
            Some(poly(vec![A], ty_list(b, Type::Var(A))))
        }
        (STD_LIST, "length") => {
            // forall a. List a -> Int
            Some(poly(
                vec![A],
                ty_fn_pure(vec![ty_list(b, Type::Var(A))], ty_int(b)),
            ))
        }
        (STD_LIST, "isEmpty") => {
            // forall a. List a -> Bool
            Some(poly(
                vec![A],
                ty_fn_pure(vec![ty_list(b, Type::Var(A))], ty_bool(b)),
            ))
        }
        (STD_LIST, "head") => {
            // forall a. List a -> Option a
            Some(poly(
                vec![A],
                ty_fn_pure(vec![ty_list(b, Type::Var(A))], ty_option(b, Type::Var(A))),
            ))
        }
        (STD_LIST, "tail") => {
            // forall a. List a -> Option (List a)
            Some(poly(
                vec![A],
                ty_fn_pure(
                    vec![ty_list(b, Type::Var(A))],
                    ty_option(b, ty_list(b, Type::Var(A))),
                ),
            ))
        }
        (STD_LIST, "cons") => {
            // forall a. a -> List a -> List a
            Some(poly(
                vec![A],
                ty_fn_pure(
                    vec![Type::Var(A), ty_list(b, Type::Var(A))],
                    ty_list(b, Type::Var(A)),
                ),
            ))
        }
        (STD_LIST, "map") => {
            // forall a b c. (fn c (a -> b)) -> List a -> List b
            Some(poly_cap(
                vec![A, B_VAR],
                vec![CAP_C],
                ty_fn_pure(
                    vec![
                        ty_fn_cap_var(vec![Type::Var(A)], Type::Var(B_VAR), CAP_C),
                        ty_list(b, Type::Var(A)),
                    ],
                    ty_list(b, Type::Var(B_VAR)),
                ),
            ))
        }
        (STD_LIST, "filter") => {
            // forall a c. (fn c (a -> Bool)) -> List a -> List a
            Some(poly_cap(
                vec![A],
                vec![CAP_C],
                ty_fn_pure(
                    vec![
                        ty_fn_cap_var(vec![Type::Var(A)], ty_bool(b), CAP_C),
                        ty_list(b, Type::Var(A)),
                    ],
                    ty_list(b, Type::Var(A)),
                ),
            ))
        }
        (STD_LIST, "filterMap") => {
            // forall a b c. (fn c (a -> Option b)) -> List a -> List b
            Some(poly_cap(
                vec![A, B_VAR],
                vec![CAP_C],
                ty_fn_pure(
                    vec![
                        ty_fn_cap_var(vec![Type::Var(A)], ty_option(b, Type::Var(B_VAR)), CAP_C),
                        ty_list(b, Type::Var(A)),
                    ],
                    ty_list(b, Type::Var(B_VAR)),
                ),
            ))
        }
        (STD_LIST, "fold") => {
            // forall a b c. (fn c (b -> a -> b)) -> b -> List a -> b
            Some(poly_cap(
                vec![A, B_VAR],
                vec![CAP_C],
                ty_fn_pure(
                    vec![
                        ty_fn_cap_var(
                            vec![Type::Var(B_VAR), Type::Var(A)],
                            Type::Var(B_VAR),
                            CAP_C,
                        ),
                        Type::Var(B_VAR),
                        ty_list(b, Type::Var(A)),
                    ],
                    Type::Var(B_VAR),
                ),
            ))
        }
        (STD_LIST, "foldRight") => {
            // forall a b c. (fn c (a -> b -> b)) -> b -> List a -> b
            Some(poly_cap(
                vec![A, B_VAR],
                vec![CAP_C],
                ty_fn_pure(
                    vec![
                        ty_fn_cap_var(
                            vec![Type::Var(A), Type::Var(B_VAR)],
                            Type::Var(B_VAR),
                            CAP_C,
                        ),
                        Type::Var(B_VAR),
                        ty_list(b, Type::Var(A)),
                    ],
                    Type::Var(B_VAR),
                ),
            ))
        }
        (STD_LIST, "reverse") => {
            // forall a. List a -> List a
            Some(poly(
                vec![A],
                ty_fn_pure(vec![ty_list(b, Type::Var(A))], ty_list(b, Type::Var(A))),
            ))
        }
        (STD_LIST, "concat") => {
            // forall a. List a -> List a -> List a
            Some(poly(
                vec![A],
                ty_fn_pure(
                    vec![ty_list(b, Type::Var(A)), ty_list(b, Type::Var(A))],
                    ty_list(b, Type::Var(A)),
                ),
            ))
        }
        (STD_LIST, "sort") => {
            // forall a. List a -> List a  (requires ord — simplified for Phase 4)
            Some(poly(
                vec![A],
                ty_fn_pure(vec![ty_list(b, Type::Var(A))], ty_list(b, Type::Var(A))),
            ))
        }
        (STD_LIST, "sortBy") => {
            // forall a b c. (fn c (a -> b)) -> List a -> List a  (key fn)
            Some(poly_cap(
                vec![A, B_VAR],
                vec![CAP_C],
                ty_fn_pure(
                    vec![
                        ty_fn_cap_var(vec![Type::Var(A)], Type::Var(B_VAR), CAP_C),
                        ty_list(b, Type::Var(A)),
                    ],
                    ty_list(b, Type::Var(A)),
                ),
            ))
        }
        (STD_LIST, "take" | "drop") => {
            // forall a. Int -> List a -> List a
            Some(poly(
                vec![A],
                ty_fn_pure(
                    vec![ty_int(b), ty_list(b, Type::Var(A))],
                    ty_list(b, Type::Var(A)),
                ),
            ))
        }
        (STD_LIST, "groupBy") => {
            // forall a b c. (fn c (a -> b)) -> List a -> Map b (List a)
            Some(poly_cap(
                vec![A, B_VAR],
                vec![CAP_C],
                ty_fn_pure(
                    vec![
                        ty_fn_cap_var(vec![Type::Var(A)], Type::Var(B_VAR), CAP_C),
                        ty_list(b, Type::Var(A)),
                    ],
                    ty_map(b, Type::Var(B_VAR), ty_list(b, Type::Var(A))),
                ),
            ))
        }
        (STD_LIST, "flatMap") => {
            // forall a b c. (fn c (a -> List b)) -> List a -> List b
            Some(poly_cap(
                vec![A, B_VAR],
                vec![CAP_C],
                ty_fn_pure(
                    vec![
                        ty_fn_cap_var(vec![Type::Var(A)], ty_list(b, Type::Var(B_VAR)), CAP_C),
                        ty_list(b, Type::Var(A)),
                    ],
                    ty_list(b, Type::Var(B_VAR)),
                ),
            ))
        }
        (STD_LIST, "zip") => {
            // forall a b. List a -> List b -> List (Tuple a b)
            // Tuples in Ridge: use Type::Tuple
            Some(poly(
                vec![A, B_VAR],
                ty_fn_pure(
                    vec![ty_list(b, Type::Var(A)), ty_list(b, Type::Var(B_VAR))],
                    ty_list(b, Type::Tuple(vec![Type::Var(A), Type::Var(B_VAR)])),
                ),
            ))
        }
        (STD_LIST, "zipWith") => {
            // forall a b c cap. (fn cap (a -> b -> c)) -> List a -> List b -> List c
            Some(poly_cap(
                vec![A, B_VAR, C_VAR],
                vec![CAP_C],
                ty_fn_pure(
                    vec![
                        ty_fn_cap_var(
                            vec![Type::Var(A), Type::Var(B_VAR)],
                            Type::Var(C_VAR),
                            CAP_C,
                        ),
                        ty_list(b, Type::Var(A)),
                        ty_list(b, Type::Var(B_VAR)),
                    ],
                    ty_list(b, Type::Var(C_VAR)),
                ),
            ))
        }
        (STD_LIST, "contains") => {
            // forall a. List a -> a -> Bool
            Some(poly(
                vec![A],
                ty_fn_pure(vec![ty_list(b, Type::Var(A)), Type::Var(A)], ty_bool(b)),
            ))
        }
        (STD_LIST, "find") => {
            // forall a c. (fn c (a -> Bool)) -> List a -> Option a
            Some(poly_cap(
                vec![A],
                vec![CAP_C],
                ty_fn_pure(
                    vec![
                        ty_fn_cap_var(vec![Type::Var(A)], ty_bool(b), CAP_C),
                        ty_list(b, Type::Var(A)),
                    ],
                    ty_option(b, Type::Var(A)),
                ),
            ))
        }
        (STD_LIST, "any" | "all") => {
            // forall a c. (fn c (a -> Bool)) -> List a -> Bool
            Some(poly_cap(
                vec![A],
                vec![CAP_C],
                ty_fn_pure(
                    vec![
                        ty_fn_cap_var(vec![Type::Var(A)], ty_bool(b), CAP_C),
                        ty_list(b, Type::Var(A)),
                    ],
                    ty_bool(b),
                ),
            ))
        }
        (STD_LIST, "range" | "rangeExclusive") => {
            // Int -> Int -> List Int
            Some(mono(ty_fn_pure(
                vec![ty_int(b), ty_int(b)],
                ty_list(b, ty_int(b)),
            )))
        }
        (STD_LIST, "forEach") => {
            // forall a c. (fn c (a -> Unit)) -> List a -> Unit
            Some(poly_cap(
                vec![A],
                vec![CAP_C],
                ty_fn_pure(
                    vec![
                        ty_fn_cap_var(vec![Type::Var(A)], ty_unit(b), CAP_C),
                        ty_list(b, Type::Var(A)),
                    ],
                    ty_unit(b),
                ),
            ))
        }

        // ── std.map ───────────────────────────────────────────────────────────
        (STD_MAP, "empty") => {
            // forall k v. Map k v
            Some(poly(
                vec![A, B_VAR],
                ty_map(b, Type::Var(A), Type::Var(B_VAR)),
            ))
        }
        (STD_MAP, "fromList") => {
            // forall k v. List (Tuple k v) -> Map k v
            Some(poly(
                vec![A, B_VAR],
                ty_fn_pure(
                    vec![ty_list(
                        b,
                        Type::Tuple(vec![Type::Var(A), Type::Var(B_VAR)]),
                    )],
                    ty_map(b, Type::Var(A), Type::Var(B_VAR)),
                ),
            ))
        }
        (STD_MAP, "toList" | "entries") => {
            // forall k v. Map k v -> List (Tuple k v)
            Some(poly(
                vec![A, B_VAR],
                ty_fn_pure(
                    vec![ty_map(b, Type::Var(A), Type::Var(B_VAR))],
                    ty_list(b, Type::Tuple(vec![Type::Var(A), Type::Var(B_VAR)])),
                ),
            ))
        }
        (STD_MAP, "insert") => {
            // forall k v. k -> v -> Map k v -> Map k v
            Some(poly(
                vec![A, B_VAR],
                ty_fn_pure(
                    vec![
                        Type::Var(A),
                        Type::Var(B_VAR),
                        ty_map(b, Type::Var(A), Type::Var(B_VAR)),
                    ],
                    ty_map(b, Type::Var(A), Type::Var(B_VAR)),
                ),
            ))
        }
        (STD_MAP, "remove") => {
            // forall k v. k -> Map k v -> Map k v
            Some(poly(
                vec![A, B_VAR],
                ty_fn_pure(
                    vec![Type::Var(A), ty_map(b, Type::Var(A), Type::Var(B_VAR))],
                    ty_map(b, Type::Var(A), Type::Var(B_VAR)),
                ),
            ))
        }
        (STD_MAP, "get") => {
            // forall k v. k -> Map k v -> Option v
            Some(poly(
                vec![A, B_VAR],
                ty_fn_pure(
                    vec![Type::Var(A), ty_map(b, Type::Var(A), Type::Var(B_VAR))],
                    ty_option(b, Type::Var(B_VAR)),
                ),
            ))
        }
        (STD_MAP, "getOr") => {
            // forall k v. k -> v -> Map k v -> v
            Some(poly(
                vec![A, B_VAR],
                ty_fn_pure(
                    vec![
                        Type::Var(A),
                        Type::Var(B_VAR),
                        ty_map(b, Type::Var(A), Type::Var(B_VAR)),
                    ],
                    Type::Var(B_VAR),
                ),
            ))
        }
        (STD_MAP, "contains") => {
            // forall k v. k -> Map k v -> Bool
            Some(poly(
                vec![A, B_VAR],
                ty_fn_pure(
                    vec![Type::Var(A), ty_map(b, Type::Var(A), Type::Var(B_VAR))],
                    ty_bool(b),
                ),
            ))
        }
        (STD_MAP, "keys") => {
            // forall k v. Map k v -> List k
            Some(poly(
                vec![A, B_VAR],
                ty_fn_pure(
                    vec![ty_map(b, Type::Var(A), Type::Var(B_VAR))],
                    ty_list(b, Type::Var(A)),
                ),
            ))
        }
        (STD_MAP, "values") => {
            // forall k v. Map k v -> List v
            Some(poly(
                vec![A, B_VAR],
                ty_fn_pure(
                    vec![ty_map(b, Type::Var(A), Type::Var(B_VAR))],
                    ty_list(b, Type::Var(B_VAR)),
                ),
            ))
        }
        (STD_MAP, "map") => {
            // forall k v1 v2 c. (fn c (k -> v1 -> v2)) -> Map k v1 -> Map k v2
            Some(poly_cap(
                vec![A, B_VAR, C_VAR],
                vec![CAP_C],
                ty_fn_pure(
                    vec![
                        ty_fn_cap_var(
                            vec![Type::Var(A), Type::Var(B_VAR)],
                            Type::Var(C_VAR),
                            CAP_C,
                        ),
                        ty_map(b, Type::Var(A), Type::Var(B_VAR)),
                    ],
                    ty_map(b, Type::Var(A), Type::Var(C_VAR)),
                ),
            ))
        }
        (STD_MAP, "filter") => {
            // forall k v c. (fn c (k -> v -> Bool)) -> Map k v -> Map k v
            Some(poly_cap(
                vec![A, B_VAR],
                vec![CAP_C],
                ty_fn_pure(
                    vec![
                        ty_fn_cap_var(vec![Type::Var(A), Type::Var(B_VAR)], ty_bool(b), CAP_C),
                        ty_map(b, Type::Var(A), Type::Var(B_VAR)),
                    ],
                    ty_map(b, Type::Var(A), Type::Var(B_VAR)),
                ),
            ))
        }
        (STD_MAP, "size") => {
            // forall k v. Map k v -> Int
            Some(poly(
                vec![A, B_VAR],
                ty_fn_pure(vec![ty_map(b, Type::Var(A), Type::Var(B_VAR))], ty_int(b)),
            ))
        }
        (STD_MAP, "merge") => {
            // forall k v. Map k v -> Map k v -> Map k v
            Some(poly(
                vec![A, B_VAR],
                ty_fn_pure(
                    vec![
                        ty_map(b, Type::Var(A), Type::Var(B_VAR)),
                        ty_map(b, Type::Var(A), Type::Var(B_VAR)),
                    ],
                    ty_map(b, Type::Var(A), Type::Var(B_VAR)),
                ),
            ))
        }
        (STD_MAP, "update") => {
            // forall k v c. k -> (fn c (Option v -> Option v)) -> Map k v -> Map k v
            Some(poly_cap(
                vec![A, B_VAR],
                vec![CAP_C],
                ty_fn_pure(
                    vec![
                        Type::Var(A),
                        ty_fn_cap_var(
                            vec![ty_option(b, Type::Var(B_VAR))],
                            ty_option(b, Type::Var(B_VAR)),
                            CAP_C,
                        ),
                        ty_map(b, Type::Var(A), Type::Var(B_VAR)),
                    ],
                    ty_map(b, Type::Var(A), Type::Var(B_VAR)),
                ),
            ))
        }

        // ── std.set ───────────────────────────────────────────────────────────
        (STD_SET, "empty") => {
            // forall a. Set a
            Some(poly(vec![A], ty_set(b, Type::Var(A))))
        }
        (STD_SET, "fromList") => {
            // forall a. List a -> Set a
            Some(poly(
                vec![A],
                ty_fn_pure(vec![ty_list(b, Type::Var(A))], ty_set(b, Type::Var(A))),
            ))
        }
        (STD_SET, "toList") => {
            // forall a. Set a -> List a
            Some(poly(
                vec![A],
                ty_fn_pure(vec![ty_set(b, Type::Var(A))], ty_list(b, Type::Var(A))),
            ))
        }
        (STD_SET, "insert" | "remove") => {
            // forall a. a -> Set a -> Set a
            Some(poly(
                vec![A],
                ty_fn_pure(
                    vec![Type::Var(A), ty_set(b, Type::Var(A))],
                    ty_set(b, Type::Var(A)),
                ),
            ))
        }
        (STD_SET, "contains") => {
            // forall a. a -> Set a -> Bool
            Some(poly(
                vec![A],
                ty_fn_pure(vec![Type::Var(A), ty_set(b, Type::Var(A))], ty_bool(b)),
            ))
        }
        (STD_SET, "union" | "intersect" | "intersection" | "difference") => {
            // forall a. Set a -> Set a -> Set a
            Some(poly(
                vec![A],
                ty_fn_pure(
                    vec![ty_set(b, Type::Var(A)), ty_set(b, Type::Var(A))],
                    ty_set(b, Type::Var(A)),
                ),
            ))
        }
        (STD_SET, "size") => {
            // forall a. Set a -> Int
            Some(poly(
                vec![A],
                ty_fn_pure(vec![ty_set(b, Type::Var(A))], ty_int(b)),
            ))
        }

        // ── std.option ────────────────────────────────────────────────────────
        (STD_OPTION, "withDefault") => {
            // forall a. a -> Option a -> a
            Some(poly(
                vec![A],
                ty_fn_pure(vec![Type::Var(A), ty_option(b, Type::Var(A))], Type::Var(A)),
            ))
        }
        (STD_OPTION, "map") => {
            // forall a b c. (fn c (a -> b)) -> Option a -> Option b
            Some(poly_cap(
                vec![A, B_VAR],
                vec![CAP_C],
                ty_fn_pure(
                    vec![
                        ty_fn_cap_var(vec![Type::Var(A)], Type::Var(B_VAR), CAP_C),
                        ty_option(b, Type::Var(A)),
                    ],
                    ty_option(b, Type::Var(B_VAR)),
                ),
            ))
        }
        (STD_OPTION, "flatMap" | "andThen") => {
            // forall a b c. (fn c (a -> Option b)) -> Option a -> Option b
            Some(poly_cap(
                vec![A, B_VAR],
                vec![CAP_C],
                ty_fn_pure(
                    vec![
                        ty_fn_cap_var(vec![Type::Var(A)], ty_option(b, Type::Var(B_VAR)), CAP_C),
                        ty_option(b, Type::Var(A)),
                    ],
                    ty_option(b, Type::Var(B_VAR)),
                ),
            ))
        }
        (STD_OPTION, "orElse") => {
            // forall a c. (fn c () -> Option a) -> Option a -> Option a
            Some(poly_cap(
                vec![A],
                vec![CAP_C],
                ty_fn_pure(
                    vec![
                        ty_fn_cap_var(vec![], ty_option(b, Type::Var(A)), CAP_C),
                        ty_option(b, Type::Var(A)),
                    ],
                    ty_option(b, Type::Var(A)),
                ),
            ))
        }
        (STD_OPTION, "isSome" | "isNone") => {
            // forall a. Option a -> Bool
            Some(poly(
                vec![A],
                ty_fn_pure(vec![ty_option(b, Type::Var(A))], ty_bool(b)),
            ))
        }
        (STD_OPTION, "discard") => {
            // forall a. Option a -> Unit
            Some(poly(
                vec![A],
                ty_fn_pure(vec![ty_option(b, Type::Var(A))], ty_unit(b)),
            ))
        }
        (STD_OPTION, "unwrapOr") => {
            // forall a. a -> Option a -> a  (alias for withDefault)
            Some(poly(
                vec![A],
                ty_fn_pure(vec![Type::Var(A), ty_option(b, Type::Var(A))], Type::Var(A)),
            ))
        }
        (STD_OPTION, "mapOr") => {
            // forall a b c. b -> (fn c (a -> b)) -> Option a -> b
            Some(poly_cap(
                vec![A, B_VAR],
                vec![CAP_C],
                ty_fn_pure(
                    vec![
                        Type::Var(B_VAR),
                        ty_fn_cap_var(vec![Type::Var(A)], Type::Var(B_VAR), CAP_C),
                        ty_option(b, Type::Var(A)),
                    ],
                    Type::Var(B_VAR),
                ),
            ))
        }
        // Type / constructor names exposed from std.option
        (STD_OPTION, "Option") => {
            // The type itself — forall a. Type (Option a).
            // Exposed as a TyCon reference; return a monomorphic TyConId scheme.
            // TODO: hand-curated stub — replace with generated table
            stub_phase7()
        }
        (STD_OPTION, "Some") => {
            // forall a. a -> Option a
            Some(poly(
                vec![A],
                ty_fn_pure(vec![Type::Var(A)], ty_option(b, Type::Var(A))),
            ))
        }
        (STD_OPTION, "None") => {
            // forall a. Option a
            Some(poly(vec![A], ty_option(b, Type::Var(A))))
        }

        // ── std.result ────────────────────────────────────────────────────────
        (STD_RESULT, "map") => {
            // forall a b e c. (fn c (a -> b)) -> Result a e -> Result b e
            Some(poly_cap(
                vec![A, B_VAR, C_VAR],
                vec![CAP_C],
                ty_fn_pure(
                    vec![
                        ty_fn_cap_var(vec![Type::Var(A)], Type::Var(B_VAR), CAP_C),
                        ty_result(b, Type::Var(A), Type::Var(C_VAR)),
                    ],
                    ty_result(b, Type::Var(B_VAR), Type::Var(C_VAR)),
                ),
            ))
        }
        (STD_RESULT, "mapErr") => {
            // forall a e1 e2 c. (fn c (e1 -> e2)) -> Result a e1 -> Result a e2
            Some(poly_cap(
                vec![A, B_VAR, C_VAR],
                vec![CAP_C],
                ty_fn_pure(
                    vec![
                        ty_fn_cap_var(vec![Type::Var(B_VAR)], Type::Var(C_VAR), CAP_C),
                        ty_result(b, Type::Var(A), Type::Var(B_VAR)),
                    ],
                    ty_result(b, Type::Var(A), Type::Var(C_VAR)),
                ),
            ))
        }
        (STD_RESULT, "flatMap" | "andThen") => {
            // forall a b e c. (fn c (a -> Result b e)) -> Result a e -> Result b e
            Some(poly_cap(
                vec![A, B_VAR, C_VAR],
                vec![CAP_C],
                ty_fn_pure(
                    vec![
                        ty_fn_cap_var(
                            vec![Type::Var(A)],
                            ty_result(b, Type::Var(B_VAR), Type::Var(C_VAR)),
                            CAP_C,
                        ),
                        ty_result(b, Type::Var(A), Type::Var(C_VAR)),
                    ],
                    ty_result(b, Type::Var(B_VAR), Type::Var(C_VAR)),
                ),
            ))
        }
        (STD_RESULT, "traverse") => {
            // forall a b e c. (fn c (a -> Result b e)) -> List a -> Result (List b) e
            Some(poly_cap(
                vec![A, B_VAR, C_VAR],
                vec![CAP_C],
                ty_fn_pure(
                    vec![
                        ty_fn_cap_var(
                            vec![Type::Var(A)],
                            ty_result(b, Type::Var(B_VAR), Type::Var(C_VAR)),
                            CAP_C,
                        ),
                        ty_list(b, Type::Var(A)),
                    ],
                    ty_result(b, ty_list(b, Type::Var(B_VAR)), Type::Var(C_VAR)),
                ),
            ))
        }
        (STD_RESULT, "sequence") => {
            // forall a e. List (Result a e) -> Result (List a) e
            Some(poly(
                vec![A, B_VAR],
                ty_fn_pure(
                    vec![ty_list(b, ty_result(b, Type::Var(A), Type::Var(B_VAR)))],
                    ty_result(b, ty_list(b, Type::Var(A)), Type::Var(B_VAR)),
                ),
            ))
        }
        (STD_RESULT, "withDefault" | "unwrapOr") => {
            // forall a e. a -> Result a e -> a
            Some(poly(
                vec![A, B_VAR],
                ty_fn_pure(
                    vec![Type::Var(A), ty_result(b, Type::Var(A), Type::Var(B_VAR))],
                    Type::Var(A),
                ),
            ))
        }
        (STD_RESULT, "isOk" | "isErr") => {
            // forall a e. Result a e -> Bool
            Some(poly(
                vec![A, B_VAR],
                ty_fn_pure(
                    vec![ty_result(b, Type::Var(A), Type::Var(B_VAR))],
                    ty_bool(b),
                ),
            ))
        }
        (STD_RESULT, "discard") => {
            // forall a e. Result a e -> Unit
            Some(poly(
                vec![A, B_VAR],
                ty_fn_pure(
                    vec![ty_result(b, Type::Var(A), Type::Var(B_VAR))],
                    ty_unit(b),
                ),
            ))
        }
        // Type / constructor names exposed from std.result
        (STD_RESULT, "Result") => {
            // TODO: hand-curated stub — replace with generated table
            stub_phase7()
        }
        (STD_RESULT, "Ok") => {
            // forall a e. a -> Result a e
            Some(poly(
                vec![A, B_VAR],
                ty_fn_pure(
                    vec![Type::Var(A)],
                    ty_result(b, Type::Var(A), Type::Var(B_VAR)),
                ),
            ))
        }
        (STD_RESULT, "Err") => {
            // forall a e. e -> Result a e
            Some(poly(
                vec![A, B_VAR],
                ty_fn_pure(
                    vec![Type::Var(B_VAR)],
                    ty_result(b, Type::Var(A), Type::Var(B_VAR)),
                ),
            ))
        }

        // ── std.test ──────────────────────────────────────────────────────────
        // Assertion helpers; each returns Result Unit Text so checks chain
        // with the `?` operator. Equality is structural, so assertEq/assertNe
        // are fully polymorphic with no typeclass bound.
        (STD_TEST, "ensure" | "assertTrue" | "assertFalse") => Some(mono(ty_fn_pure(
            vec![ty_bool(b), ty_text(b)],
            ty_result(b, ty_unit(b), ty_text(b)),
        ))),
        (STD_TEST, "assertEq" | "assertNe") => Some(poly(
            vec![A],
            ty_fn_pure(
                vec![Type::Var(A), Type::Var(A), ty_text(b)],
                ty_result(b, ty_unit(b), ty_text(b)),
            ),
        )),
        (STD_TEST, "isOk" | "isErr") => Some(poly(
            vec![A, B_VAR],
            ty_fn_pure(
                vec![
                    ty_result(b, Type::Var(A), Type::Var(B_VAR)),
                    ty_text(b),
                ],
                ty_result(b, ty_unit(b), ty_text(b)),
            ),
        )),
        (STD_TEST, "isSome" | "isNone") => Some(poly(
            vec![A],
            ty_fn_pure(
                vec![ty_option(b, Type::Var(A)), ty_text(b)],
                ty_result(b, ty_unit(b), ty_text(b)),
            ),
        )),

        // ── std.io ────────────────────────────────────────────────────────────
        //
        // All io functions carry the {io} capability set.
        (STD_IO, "print" | "println" | "eprint" | "eprintln") => {
            use ridge_ast::Capability;
            let io_caps = CapabilitySet::singleton(Capability::Io);
            Some(mono(ty_fn_caps(vec![ty_text(b)], ty_unit(b), io_caps)))
        }
        (STD_IO, "readLine") => {
            use ridge_ast::Capability;
            let io_caps = CapabilitySet::singleton(Capability::Io);
            // (_: Unit) -> Result Text Error [io]  (§3.10 / plan line 322)
            // T12: .ridge declares `(_ : Unit)` thunk param; signature updated to match.
            Some(mono(ty_fn_caps(
                vec![ty_unit(b)],
                ty_result(b, ty_text(b), ty_error(b)),
                io_caps,
            )))
        }

        // ── std.fs ────────────────────────────────────────────────────────────
        (STD_FS, "readFile" | "readText") => {
            use ridge_ast::Capability;
            let fs_caps = CapabilitySet::singleton(Capability::Fs);
            Some(mono(ty_fn_caps(
                vec![ty_text(b)],
                ty_result(b, ty_text(b), ty_text(b)),
                fs_caps,
            )))
        }
        (STD_FS, "writeFile" | "writeText" | "append") => {
            use ridge_ast::Capability;
            let fs_caps = CapabilitySet::singleton(Capability::Fs);
            Some(mono(ty_fn_caps(
                vec![ty_text(b), ty_text(b)],
                ty_result(b, ty_unit(b), ty_text(b)),
                fs_caps,
            )))
        }
        (STD_FS, "exists") => {
            use ridge_ast::Capability;
            let fs_caps = CapabilitySet::singleton(Capability::Fs);
            Some(mono(ty_fn_caps(vec![ty_text(b)], ty_bool(b), fs_caps)))
        }
        (STD_FS, "lines" | "listDir" | "readDir") => {
            use ridge_ast::Capability;
            let fs_caps = CapabilitySet::singleton(Capability::Fs);
            Some(mono(ty_fn_caps(
                vec![ty_text(b)],
                ty_result(b, ty_list(b, ty_text(b)), ty_text(b)),
                fs_caps,
            )))
        }
        (STD_FS, "isDir") => {
            use ridge_ast::Capability;
            let fs_caps = CapabilitySet::singleton(Capability::Fs);
            Some(mono(ty_fn_caps(vec![ty_text(b)], ty_bool(b), fs_caps)))
        }
        (STD_FS, "createDir" | "remove") => {
            use ridge_ast::Capability;
            let fs_caps = CapabilitySet::singleton(Capability::Fs);
            Some(mono(ty_fn_caps(
                vec![ty_text(b)],
                ty_result(b, ty_unit(b), ty_text(b)),
                fs_caps,
            )))
        }

        // ── std.time ──────────────────────────────────────────────────────────
        (STD_TIME, "now") => {
            use ridge_ast::Capability;
            let time_caps = CapabilitySet::singleton(Capability::Time);
            // T12: .ridge declares `(_ : Unit)` thunk param; signature updated to match.
            Some(mono(ty_fn_caps(vec![ty_unit(b)], ty_timestamp(b), time_caps)))
        }
        (STD_TIME, "epoch") => {
            // T12: .ridge declares `(_ : Unit)` thunk param; signature updated to match.
            // (_: Unit) -> Timestamp  (the Unix epoch)
            Some(mono(ty_fn_pure(vec![ty_unit(b)], ty_timestamp(b))))
        }
        (STD_TIME, "fromIso") => {
            // Text -> Result Timestamp Error  (pure parsing — §3.12 line 348)
            Some(mono(ty_fn_pure(
                vec![ty_text(b)],
                ty_result(b, ty_timestamp(b), ty_error(b)),
            )))
        }
        (STD_TIME, "diff") => {
            // Timestamp -> Timestamp -> Duration  (§3.12 line 349)
            Some(mono(ty_fn_pure(
                vec![ty_timestamp(b), ty_timestamp(b)],
                ty_duration(b),
            )))
        }
        (STD_TIME, "diffMs") => {
            // Timestamp -> Timestamp -> Int
            Some(mono(ty_fn_pure(
                vec![ty_timestamp(b), ty_timestamp(b)],
                ty_int(b),
            )))
        }
        (STD_TIME, "diffSeconds") => {
            // Timestamp -> Timestamp -> Float
            Some(mono(ty_fn_pure(
                vec![ty_timestamp(b), ty_timestamp(b)],
                ty_float(b),
            )))
        }
        (STD_TIME, "sinceMs") => {
            use ridge_ast::Capability;
            // Timestamp -> Int  (milliseconds since timestamp — needs time cap)
            let time_caps = CapabilitySet::singleton(Capability::Time);
            Some(mono(ty_fn_caps(
                vec![ty_timestamp(b)],
                ty_int(b),
                time_caps,
            )))
        }
        (STD_TIME, "sleep") => {
            use ridge_ast::Capability;
            // Int -> Unit  (sleep milliseconds)
            let time_caps = CapabilitySet::singleton(Capability::Time);
            Some(mono(ty_fn_caps(vec![ty_int(b)], ty_unit(b), time_caps)))
        }
        (STD_TIME, "parse") => {
            // Text -> Result Timestamp Error  (alias of fromIso — §3.12 line 353)
            Some(mono(ty_fn_pure(
                vec![ty_text(b)],
                ty_result(b, ty_timestamp(b), ty_error(b)),
            )))
        }
        (STD_TIME, "iso") => {
            // Timestamp -> Text
            Some(mono(ty_fn_pure(vec![ty_timestamp(b)], ty_text(b))))
        }

        // ── std.random ────────────────────────────────────────────────────────
        (STD_RANDOM, "int") => {
            use ridge_ast::Capability;
            let rnd_caps = CapabilitySet::singleton(Capability::Random);
            // Int -> Int -> Int  (range lo hi)
            Some(mono(ty_fn_caps(
                vec![ty_int(b), ty_int(b)],
                ty_int(b),
                rnd_caps,
            )))
        }
        (STD_RANDOM, "float") => {
            use ridge_ast::Capability;
            let rnd_caps = CapabilitySet::singleton(Capability::Random);
            // T12: .ridge declares `(_ : Unit)` thunk param; signature updated to match.
            // (_: Unit) -> Float  (uniform 0..1)
            Some(mono(ty_fn_caps(vec![ty_unit(b)], ty_float(b), rnd_caps)))
        }
        (STD_RANDOM, "alphanumeric") => {
            use ridge_ast::Capability;
            let rnd_caps = CapabilitySet::singleton(Capability::Random);
            // Int -> Text  (length n)
            Some(mono(ty_fn_caps(vec![ty_int(b)], ty_text(b), rnd_caps)))
        }
        (STD_RANDOM, "choice") => {
            use ridge_ast::Capability;
            let rnd_caps = CapabilitySet::singleton(Capability::Random);
            // forall a. List a -> Option a
            Some(Scheme {
                vars: vec![A],
                cap_vars: vec![],
                row_vars: vec![],
                ty: ty_fn_caps(
                    vec![ty_list(b, Type::Var(A))],
                    ty_option(b, Type::Var(A)),
                    rnd_caps,
                ),
                constraints: vec![],
            })
        }
        (STD_RANDOM, "seed") => {
            use ridge_ast::Capability;
            let rnd_caps = CapabilitySet::singleton(Capability::Random);
            // Int -> Unit
            Some(mono(ty_fn_caps(vec![ty_int(b)], ty_unit(b), rnd_caps)))
        }

        // ── std.env ───────────────────────────────────────────────────────────
        (STD_ENV, "get" | "getVar") => {
            use ridge_ast::Capability;
            let env_caps = CapabilitySet::singleton(Capability::Env);
            // Text -> Option Text
            Some(mono(ty_fn_caps(
                vec![ty_text(b)],
                ty_option(b, ty_text(b)),
                env_caps,
            )))
        }
        (STD_ENV, "set") => {
            use ridge_ast::Capability;
            let env_caps = CapabilitySet::singleton(Capability::Env);
            // Text -> Text -> Unit
            Some(mono(ty_fn_caps(
                vec![ty_text(b), ty_text(b)],
                ty_unit(b),
                env_caps,
            )))
        }
        (STD_ENV, "all") => {
            use ridge_ast::Capability;
            let env_caps = CapabilitySet::singleton(Capability::Env);
            // T12: .ridge declares `(_ : Unit)` thunk param; signature updated to match.
            // (_: Unit) -> Map Text Text
            Some(mono(ty_fn_caps(
                vec![ty_unit(b)],
                ty_map(b, ty_text(b), ty_text(b)),
                env_caps,
            )))
        }
        (STD_ENV | STD_CLI, "args") => {
            use ridge_ast::Capability;
            let env_caps = CapabilitySet::singleton(Capability::Env);
            // T12: .ridge declares `(_ : Unit)` thunk param; signature updated to match.
            // (_: Unit) -> List Text
            Some(mono(ty_fn_caps(
                vec![ty_unit(b)],
                ty_list(b, ty_text(b)),
                env_caps,
            )))
        }
        (STD_CLI, "exit") => {
            use ridge_ast::Capability;
            let proc_caps = CapabilitySet::singleton(Capability::Proc);
            // Int -> Unit (does not return)
            Some(mono(ty_fn_caps(vec![ty_int(b)], ty_unit(b), proc_caps)))
        }
        // ── std.proc ──────────────────────────────────────────────────────────
        (STD_PROC, "run") => {
            use ridge_ast::Capability;
            let proc_caps = CapabilitySet::singleton(Capability::Proc);
            // Text -> List Text -> Result ProcOutput Error  (§3.16 / OQ-S007 / D123)
            Some(mono(ty_fn_caps(
                vec![ty_text(b), ty_list(b, ty_text(b))],
                ty_result(b, ty_proc_output(b), ty_error(b)),
                proc_caps,
            )))
        }

        // ── std.actor ─────────────────────────────────────────────────────────
        (STD_ACTOR, "mailboxSize") => {
            // forall a. Handle a -> Option Int  (cap-free; the handle is the
            // proof of access — see spec §6.4.1).
            Some(poly(
                vec![A],
                ty_fn_pure(vec![ty_handle(b, Type::Var(A))], ty_option(b, ty_int(b))),
            ))
        }

        // ── std.json ─────────────────────────────────────────────────────────
        //
        // §3.17: JsonValue is now a prelude union (BuiltinTyCons::json_value),
        // so the two bridge functions carry real signatures. The `J*` variants
        // and the `JsonValue` type name are prelude symbols, not std.json
        // exports — they are typed by `prelude.rs`, not here.
        //
        // encode : JsonValue -> Text
        (STD_JSON, "encode") => Some(mono(ty_fn_pure(
            vec![ty_json_value(b)],
            ty_text(b),
        ))),
        // decode : Text -> Result JsonValue Error
        (STD_JSON, "decode") => Some(mono(ty_fn_pure(
            vec![ty_text(b)],
            ty_result(b, ty_json_value(b), ty_error(b)),
        ))),

        // The remaining std.json surface (the pure encode helpers, the FFI
        // construction shims, and the accessor companions) is still stubbed —
        // see the shared stub arm below.
        //
        // ── std.cli (partial stubs) ───────────────────────────────────────────
        // ── std.net.http (partial stubs) ──────────────────────────────────────
        //
        // Request and Response are record TyCons that don't exist in Phase 4's
        // arena; handler shapes are deferred to a later pass.
        //
        // TODO: replace stubs with generated signatures.
        //
        // T12: `pub type Duration` (time.ridge) and `pub type ProcOutput` (proc.ridge) are
        // record TyCons declared in the stdlib source; they don't have stable TyConIds
        // in BuiltinTyCons so we use stub_phase7() for now.
        (STD_TIME, "Duration")
        | (STD_PROC, "ProcOutput")
        | (STD_JSON,
           "encodeInt" | "encodeBool" | "encodeText"
           // JsonValue construction shims (FFI bridges to ridge_rt:json_*).
           // The first-class `J*` constructors are prelude-typed; these shims
           // remain for callers that already use them.
           | "jNull" | "jBool" | "jInt" | "jFloat" | "jText" | "jList" | "jObject"
           // JsonValue accessor companions — peel one variant off a decoded
           // JsonValue as an Option-shaped escape hatch.
           | "asInt" | "asFloat" | "asBool" | "asText" | "asList" | "asObject" | "isNull")
        | (STD_CLI, "parseArgs" | "help" | "version")
        | (STD_NET_HTTP,
           "get" | "post" | "put" | "delete" | "respond" | "Request" | "Response"
           // `Html` / `SecureCookie` as a bare value (the constructor) stay
           // stubbed — the resolver rejects constructing them from user code
           // (R025). `Sql` is the same, declared under std.sql.
           | "Html" | "SecureCookie")
        | (STD_SQL, "Sql") => {
            stub_phase7()
        }

        // Safe-text taint wrappers: `sql` (std.sql) and `html` (std.net.http)
        // escape raw text into an opaque wrapper; `sqlValue`/`htmlValue` read the
        // escaped text back out (the only way to do so, since the field is opaque
        // outside the declaring module).
        (STD_SQL, "sql") => Some(mono(ty_fn_pure(
            vec![ty_text(b)],
            Type::Con(b.sql, vec![]),
        ))),
        (STD_SQL, "sqlValue") => Some(mono(ty_fn_pure(
            vec![Type::Con(b.sql, vec![])],
            ty_text(b),
        ))),
        // Monomorphic SqlValue factories — turn a base value into the opaque
        // bind type without the `SqlType` class machinery.
        (STD_SQL, "sqlInt") => Some(mono(ty_fn_pure(
            vec![ty_int(b)],
            Type::Con(b.sql_value, vec![]),
        ))),
        (STD_SQL, "sqlText") => Some(mono(ty_fn_pure(
            vec![ty_text(b)],
            Type::Con(b.sql_value, vec![]),
        ))),
        (STD_SQL, "sqlBool") => Some(mono(ty_fn_pure(
            vec![ty_bool(b)],
            Type::Con(b.sql_value, vec![]),
        ))),
        (STD_SQL, "sqlFloat") => Some(mono(ty_fn_pure(
            vec![ty_float(b)],
            Type::Con(b.sql_value, vec![]),
        ))),
        // The SQL NULL bind value — a nullary factory completing the set.
        (STD_SQL, "sqlNull") => Some(mono(ty_fn_pure(
            vec![],
            Type::Con(b.sql_value, vec![]),
        ))),
        // A typed SQL instant (epoch microseconds) — the timestamp bind value.
        (STD_SQL, "sqlInstant") => Some(mono(ty_fn_pure(
            vec![ty_int(b)],
            Type::Con(b.sql_value, vec![]),
        ))),
        // A typed SQL decimal (exact canonical text) — the decimal bind value.
        (STD_SQL, "sqlDecimal") => Some(mono(ty_fn_pure(
            vec![ty_text(b)],
            Type::Con(b.sql_value, vec![]),
        ))),
        // Render a SqlValue as an inline SQL literal (a DDL DEFAULT / CHECK position
        // a bind parameter cannot fill).
        (STD_SQL, "sqlLiteral") => Some(mono(ty_fn_pure(
            vec![Type::Con(b.sql_value, vec![])],
            ty_text(b),
        ))),
        // Render a SqlValue back to its Ridge source expression (the source dual of
        // `sqlLiteral`) — the migration snapshot renderer's `DefaultLit` path.
        (STD_SQL, "sqlValueSource") => Some(mono(ty_fn_pure(
            vec![Type::Con(b.sql_value, vec![])],
            ty_text(b),
        ))),
        (STD_NET_HTTP, "html") => Some(mono(ty_fn_pure(
            vec![ty_text(b)],
            Type::Con(b.html, vec![]),
        ))),
        (STD_NET_HTTP, "htmlValue") => Some(mono(ty_fn_pure(
            vec![Type::Con(b.html, vec![])],
            ty_text(b),
        ))),

        // SecureCookie: a factory with safe defaults, a header serializer, and
        // one setter per overridable attribute (the record is opaque, so `with`
        // updates from user code are rejected — the setters are the only path).
        (STD_NET_HTTP, "secureCookie") => Some(mono(ty_fn_pure(
            vec![ty_text(b), ty_text(b)],
            Type::Con(b.secure_cookie, vec![]),
        ))),
        (STD_NET_HTTP, "secureCookieHeader") => Some(mono(ty_fn_pure(
            vec![Type::Con(b.secure_cookie, vec![])],
            ty_text(b),
        ))),
        (STD_NET_HTTP, "withSecure" | "withHttpOnly") => Some(mono(ty_fn_pure(
            vec![Type::Con(b.secure_cookie, vec![]), ty_bool(b)],
            Type::Con(b.secure_cookie, vec![]),
        ))),
        (STD_NET_HTTP, "withSameSite") => Some(mono(ty_fn_pure(
            vec![Type::Con(b.secure_cookie, vec![]), ty_text(b)],
            Type::Con(b.secure_cookie, vec![]),
        ))),
        (STD_NET_HTTP, "withMaxAge") => Some(mono(ty_fn_pure(
            vec![
                Type::Con(b.secure_cookie, vec![]),
                Type::Con(b.option, vec![ty_int(b)]),
            ],
            Type::Con(b.secure_cookie, vec![]),
        ))),
        (STD_NET_HTTP, "withPath") => Some(mono(ty_fn_pure(
            vec![
                Type::Con(b.secure_cookie, vec![]),
                Type::Con(b.option, vec![ty_text(b)]),
            ],
            Type::Con(b.secure_cookie, vec![]),
        ))),
        // listen: Int -> (fn {net} (Request -> Response)) -> Unit
        // Phase 4: polymorphic over the handler type (Request/Response stubs).
        (STD_NET_HTTP, "listen") => Some(poly(
            vec![A, B_VAR],
            ty_fn_pure(vec![ty_int(b), Type::Var(B_VAR)], ty_unit(b)),
        )),

        // ── std.crypto ────────────────────────────────────────────────────────
        // constantTimeEq: Text -> Text -> Bool
        (STD_CRYPTO, "constantTimeEq") => Some(mono(ty_fn_pure(
            vec![ty_text(b), ty_text(b)],
            ty_bool(b),
        ))),

        // ── std.query ─────────────────────────────────────────────────────────
        // debugShow: ∀ f. Quote f -> Text — renders a captured tree.
        (STD_QUERY, "debugShow") => Some(poly(
            vec![A],
            ty_fn_pure(
                vec![Type::Con(b.quote, vec![Type::Var(A)])],
                ty_text(b),
            ),
        )),
        // toSql: ∀ f. Quote f -> (Sql, List SqlValue) — compiles a captured tree
        // to parameterized SQL plus the ordered bind values.
        (STD_QUERY, "toSql") => Some(poly(
            vec![A],
            ty_fn_pure(
                vec![Type::Con(b.quote, vec![Type::Var(A)])],
                Type::Tuple(vec![
                    Type::Con(b.sql, vec![]),
                    Type::Con(b.list, vec![Type::Con(b.sql_value, vec![])]),
                ]),
            ),
        )),
        // selectSql: ∀ f. Quote f -> (Sql, List SqlValue) — compiles a captured
        // projection into a SQL select-list and its ordered bind values; a
        // computed field (arithmetic, a CASE) contributes the binds for its
        // literals, a plain column projection none.
        (STD_QUERY, "selectSql") => Some(poly(
            vec![A],
            ty_fn_pure(
                vec![Type::Con(b.quote, vec![Type::Var(A)])],
                Type::Tuple(vec![
                    Type::Con(b.sql, vec![]),
                    Type::Con(b.list, vec![Type::Con(b.sql_value, vec![])]),
                ]),
            ),
        )),

        // ── catch-all ─────────────────────────────────────────────────────────
        _ => None,
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use ridge_types::TyConArena;

    fn builtins() -> BuiltinTyCons {
        let mut arena = TyConArena::new();
        BuiltinTyCons::allocate(&mut arena)
    }

    // ── Property test: every BUILTINS export resolves ─────────────────────────

    /// Property test: every `(module, name)` pair exported by BUILTINS must
    /// return `Some(Scheme)` from `stdlib_signature`.
    ///
    /// This is the `DoD` requirement from §10 T3 / §3.4 of the plan.
    #[test]
    #[expect(
        clippy::too_many_lines,
        reason = "one skip-guard block per reconciled stdlib module; the guards read best kept together"
    )]
    fn every_builtins_export_resolves_to_some_scheme() {
        let b = builtins();
        let mut missing: Vec<(&str, &str)> = Vec::new();
        for module in BUILTINS {
            for &name in module.exports {
                // std.sql's `SqlType`/`Row` classes, their methods (`toSql`/
                // `fromSql`/`dbType`/`fromRow`/`toRow`/`rowColumns`, seeded via
                // `seed_sql_codec_schemes` rather than this signature table), and the
                // opaque `SqlValue` type are not value schemes, so they have no
                // `stdlib_signature` entry. `DbType` and its constructors are a
                // reconciled union seeded from the reserved arena block
                // (`reconciled_ctor_scheme`, like std.schema's descriptor types); it
                // lives here beside `SqlValue` so the `SqlType` codec class can name it.
                if module.name == "std.sql"
                    && matches!(
                        name,
                        "SqlValue"
                            | "SqlType"
                            | "toSql"
                            | "fromSql"
                            | "dbType"
                            | "Row"
                            | "fromRow"
                            | "toRow"
                            | "rowColumns"
                            | "DbType"
                            | "DbBoolean"
                            | "DbInt"
                            | "DbBigInt"
                            | "DbFloat"
                            | "DbDecimal"
                            | "DbText"
                            | "DbVarchar"
                            | "DbUuid"
                            | "DbTimestamp"
                            | "DbTimestampTz"
                            | "DbRaw"
                    )
                {
                    continue;
                }
                // std.decimal's reconciled `RoundingMode`: the type is seeded from
                // the reserved arena block, its constructors from
                // `reconciled_ctor_scheme`, and the `round`/`div` functions that name
                // it from `reconciled_fn_scheme` — none via this hand-curated table.
                if module.name == "std.decimal"
                    && matches!(
                        name,
                        "RoundingMode"
                            | "HalfEven"
                            | "HalfUp"
                            | "HalfDown"
                            | "Up"
                            | "Down"
                            | "Ceiling"
                            | "Floor"
                            | "round"
                            | "div"
                    )
                {
                    continue;
                }
                // std.query's reconciled types: `SortOrder` is a type (no value
                // scheme), `Asc`/`Desc` are constructors resolved from the
                // reserved arena block (`reconciled_ctor_scheme`), and `orderSql`
                // is a function whose signature references `SortOrder`, so it is
                // seeded via `reconciled_fn_scheme` rather than this table.
                if module.name == "std.query"
                    && matches!(
                        name,
                        "SortOrder"
                            | "Asc"
                            | "Desc"
                            | "orderSql"
                            | "ascending"
                            // The reconciled `QueryPlan` tree, its constructors, and
                            // its builders are seeded via `reconciled_decls` /
                            // `reconciled_ctor_scheme` / `reconciled_fn_scheme`, not
                            // this hand-curated table.
                            | "QueryPlan"
                            | "PlanScan"
                            | "PlanCombine"
                            | "PlanRefine"
                            | "PlanJoin"
                            | "PlanProject"
                            | "PlanAggregate"
                            | "PlanGroup"
                            | "PlanExists"
                            | "PlanList"
                            | "planScan"
                            | "planCombine"
                            | "planRefine"
                            | "planJoin"
                            | "planProject"
                            | "planAggregate"
                            | "planGroup"
                            // `planToSql` takes the reconciled `QueryPlan`, so its
                            // scheme is seeded via `reconciled_query_plan_fn_scheme`,
                            // not this hand-curated table. `optimize` takes and returns
                            // one, so it is seeded the same way.
                            | "planToSql"
                            | "optimize"
                            | "planExists"
                            | "planList"
                            // The reconciled `MutationPlan` tree, its constructors, the
                            // builders, and the write-side renderer `mutationToSql` are
                            // seeded via `reconciled_decls` / `reconciled_ctor_scheme` /
                            // `reconciled_mutation_plan_fn_scheme`, not this table.
                            | "MutationPlan"
                            | "MutInsert"
                            | "MutUpsert"
                            | "MutUpdate"
                            | "MutDelete"
                            | "MutDeleteKeys"
                            | "planInsert"
                            | "planUpsert"
                            | "planUpdate"
                            | "planDelete"
                            | "planDeleteKeys"
                            | "mutationToSql"
                            | "mutationReturningToSql"
                    )
                {
                    continue;
                }
                // std.data: the `Adapter` class and its methods (`appendRow`/`all`/
                // `get`/`delete`/`updateRows`/`runPlan`) are seeded
                // via `seed_sql_codec_schemes`;
                // the `selectRows`/`fetch` read helpers are standalone functions seeded
                // via `reconciled_fn_scheme` (their quoted predicate pins the entity);
                // `MemAdapter`/`Postgres`/`Config` are reconciled types, and
                // `memAdapter`/`connect` are seeded via `reconciled_fn_scheme`
                // (their signatures name reconciled types), so none resolves
                // through this hand-curated table.
                if module.name == "std.data"
                    && matches!(
                        name,
                        "Adapter"
                            | "appendRow"
                            | "all"
                            | "selectRows"
                            | "get"
                            | "delete"
                            | "updateRows"
                            | "fetch"
                            | "runPlan"
                            | "runMutation"
                            | "runMutationReturning"
                            | "begin"
                            | "commit"
                            | "rollback"
                            | "close"
                            | "ddlCreate"
                            | "ddlDrop"
                            | "ddlAddColumn"
                            | "ddlDropColumn"
                            | "ddlIndex"
                            | "ddlDropIndex"
                            | "ddlCreateEntity"
                            | "ddlAddEntityColumn"
                            | "ddlAlterColumn"
                            | "migrationsApplied"
                            | "recordMigration"
                            | "unrecordMigration"
                            | "rawQuery"
                            | "rawExec"
                            | "MemAdapter"
                            | "memAdapter"
                            | "Postgres"
                            | "Config"
                            | "connect"
                            | "PoolConfig"
                            | "connectWith"
                            | "defaultPool"
                            | "withPoolSize"
                            | "withConnectTimeoutMs"
                            | "withQueryTimeoutMs"
                            | "withCheckoutTimeoutMs"
                            | "withIdleTimeoutMs"
                            | "withMaxLifetimeMs"
                            | "withHealthCheckMs"
                            | "withConnectRetries"
                            | "withRetryBackoffMs"
                            | "withMaxQueueDepth"
                            // Typed database errors: the reconciled `DbErrorKind`
                            // union, its variants, the classifier, and the accessors
                            // are seeded via `reconciled_decls` / `reconciled_ctor_scheme`
                            // / `reconciled_fn_scheme`, not this hand-curated table.
                            | "DbErrorKind"
                            | "UniqueViolation"
                            | "ForeignKeyViolation"
                            | "NotNullViolation"
                            | "CheckViolation"
                            | "ConnectionError"
                            | "DecodeError"
                            | "Unsupported"
                            | "QueryError"
                            | "dbErrorKind"
                            | "dbErrorConstraint"
                            | "dbErrorColumn"
                            | "dbErrorTable"
                    )
                {
                    continue;
                }
                // std.repo: the reconciled `Repo` type and every verb over it
                // are seeded from the reconciled arena block
                // (`reconciled_ctor_scheme` / `reconciled_fn_scheme`), not this
                // hand-curated table.
                if module.name == "std.repo" {
                    continue;
                }
                // std.migrate: its DSL types and builders/runner reference the
                // reconciled `Column`/`MigrationOp`/`Migration` block and are seeded
                // via `reconciled_ctor_scheme` / `reconciled_fn_scheme`, not this
                // hand-curated table.
                if module.name == "std.migrate" {
                    continue;
                }
                // std.raw: its escape-hatch verbs are constrained over `Adapter a`
                // (and `Row e` for the decoding ones), so they are seeded via
                // `reconciled_fn_scheme`, not this hand-curated table.
                if module.name == "std.raw" {
                    continue;
                }
                // std.schema: its descriptor types, their constructors, and the
                // builder/accessor functions are seeded from the reconciled arena
                // block (`reconciled_ctor_scheme` / `reconciled_fn_scheme`), not this
                // hand-curated table.
                if module.name == "std.schema" {
                    continue;
                }
                let result = stdlib_signature(module.id, name, &b);
                if result.is_none() {
                    missing.push((module.name, name));
                }
            }
        }
        assert!(
            missing.is_empty(),
            "The following BUILTINS exports have no stdlib_signature: {missing:?}"
        );
    }

    // ── std.int ───────────────────────────────────────────────────────────────

    #[test]
    fn std_int_totext_types_as_int_to_text() {
        let b = builtins();
        let scheme = stdlib_signature(STD_INT, "toText", &b).unwrap();
        assert!(scheme.vars.is_empty());
        assert!(matches!(
            scheme.ty,
            Type::Fn { ref params, .. } if params.len() == 1
        ));
    }

    #[test]
    fn std_int_parse_returns_option_int() {
        let b = builtins();
        let scheme = stdlib_signature(STD_INT, "parse", &b).unwrap();
        assert!(
            matches!(scheme.ty, Type::Fn { ref ret, .. } if matches!(ret.as_ref(), Type::Con(id, _) if *id == b.option))
        );
    }

    // ── std.float ─────────────────────────────────────────────────────────────

    #[test]
    fn std_float_sqrt_types_as_float_to_float() {
        let b = builtins();
        let scheme = stdlib_signature(STD_FLOAT, "sqrt", &b).unwrap();
        assert!(matches!(scheme.ty, Type::Fn { ref params, ref ret, .. }
            if params.len() == 1
            && matches!(ret.as_ref(), Type::Con(id, _) if *id == b.float)
        ));
    }

    // ── std.bool ──────────────────────────────────────────────────────────────

    #[test]
    fn std_bool_not_types_as_bool_to_bool() {
        let b = builtins();
        let scheme = stdlib_signature(STD_BOOL, "not", &b).unwrap();
        assert!(matches!(
            scheme.ty,
            Type::Fn { ref params, ref ret, .. }
            if params.len() == 1
            && matches!(ret.as_ref(), Type::Con(id, _) if *id == b.bool)
        ));
    }

    // ── std.text ──────────────────────────────────────────────────────────────

    #[test]
    fn std_text_split_returns_list_text() {
        let b = builtins();
        let scheme = stdlib_signature(STD_TEXT, "split", &b).unwrap();
        assert!(matches!(scheme.ty, Type::Fn { ref ret, .. }
            if matches!(ret.as_ref(), Type::Con(id, args)
                if *id == b.list && args.len() == 1
                && matches!(&args[0], Type::Con(tid, _) if *tid == b.text))
        ));
    }

    // ── std.list ──────────────────────────────────────────────────────────────

    #[test]
    fn std_list_map_is_polymorphic_with_cap_var() {
        let b = builtins();
        let scheme = stdlib_signature(STD_LIST, "map", &b).unwrap();
        // map: forall a b, cap c.
        assert_eq!(scheme.vars, vec![TyVid(0), TyVid(1)]);
        assert_eq!(scheme.cap_vars, vec![CapVid(0)]);
    }

    #[test]
    fn std_list_fold_has_three_type_vars_and_one_cap_var() {
        let b = builtins();
        let scheme = stdlib_signature(STD_LIST, "fold", &b).unwrap();
        assert_eq!(scheme.vars.len(), 2); // a, b
        assert_eq!(scheme.cap_vars.len(), 1); // c
    }

    #[test]
    fn std_list_foreach_uses_cap_var() {
        let b = builtins();
        let scheme = stdlib_signature(STD_LIST, "forEach", &b).unwrap();
        assert!(!scheme.cap_vars.is_empty());
    }

    #[test]
    fn std_list_range_is_int_int_to_list_int() {
        let b = builtins();
        let scheme = stdlib_signature(STD_LIST, "range", &b).unwrap();
        assert!(scheme.vars.is_empty());
        assert!(matches!(scheme.ty, Type::Fn { ref params, .. } if params.len() == 2));
    }

    #[test]
    fn std_list_empty_is_polymorphic() {
        let b = builtins();
        let scheme = stdlib_signature(STD_LIST, "empty", &b).unwrap();
        assert!(!scheme.vars.is_empty());
    }

    // ── std.map ───────────────────────────────────────────────────────────────

    #[test]
    fn std_map_get_returns_option() {
        let b = builtins();
        let scheme = stdlib_signature(STD_MAP, "get", &b).unwrap();
        assert!(matches!(scheme.ty, Type::Fn { ref ret, .. }
            if matches!(ret.as_ref(), Type::Con(id, _) if *id == b.option)
        ));
    }

    // ── std.set ───────────────────────────────────────────────────────────────

    #[test]
    fn std_set_size_returns_int() {
        let b = builtins();
        let scheme = stdlib_signature(STD_SET, "size", &b).unwrap();
        assert!(matches!(scheme.ty, Type::Fn { ref ret, .. }
            if matches!(ret.as_ref(), Type::Con(id, _) if *id == b.int)
        ));
    }

    // ── std.option ────────────────────────────────────────────────────────────

    #[test]
    fn std_option_some_types_correctly() {
        let b = builtins();
        let scheme = stdlib_signature(STD_OPTION, "Some", &b).unwrap();
        assert_eq!(scheme.vars, vec![TyVid(0)]);
        // Ret should be Option a
        assert!(matches!(scheme.ty, Type::Fn { ref ret, .. }
            if matches!(ret.as_ref(), Type::Con(id, _) if *id == b.option)
        ));
    }

    #[test]
    fn std_option_none_is_polymorphic_option() {
        let b = builtins();
        let scheme = stdlib_signature(STD_OPTION, "None", &b).unwrap();
        assert_eq!(scheme.vars, vec![TyVid(0)]);
        assert!(matches!(scheme.ty, Type::Con(id, _) if id == b.option));
    }

    // ── std.result ────────────────────────────────────────────────────────────

    #[test]
    fn std_result_ok_types_correctly() {
        let b = builtins();
        let scheme = stdlib_signature(STD_RESULT, "Ok", &b).unwrap();
        assert_eq!(scheme.vars.len(), 2); // a, e
        assert!(matches!(scheme.ty, Type::Fn { ref ret, .. }
            if matches!(ret.as_ref(), Type::Con(id, _) if *id == b.result)
        ));
    }

    // ── std.io ────────────────────────────────────────────────────────────────

    #[test]
    fn std_io_println_types_as_text_to_unit_with_io_cap() {
        use ridge_ast::Capability;
        let b = builtins();
        let scheme = stdlib_signature(STD_IO, "println", &b).unwrap();
        assert!(matches!(scheme.ty,
            Type::Fn { ref params, ref caps, ref ret }
            if params.len() == 1
            && matches!(ret.as_ref(), Type::Con(id, _) if *id == b.unit)
            && matches!(caps, CapRow::Concrete(cs) if cs.contains(Capability::Io))
        ));
    }

    // ── std.fs ────────────────────────────────────────────────────────────────

    #[test]
    fn std_fs_read_file_has_fs_capability() {
        use ridge_ast::Capability;
        let b = builtins();
        let scheme = stdlib_signature(STD_FS, "readFile", &b).unwrap();
        assert!(matches!(scheme.ty,
            Type::Fn { ref caps, .. }
            if matches!(caps, CapRow::Concrete(cs) if cs.contains(Capability::Fs))
        ));
    }

    // ── std.time ──────────────────────────────────────────────────────────────

    #[test]
    fn std_time_now_returns_timestamp_with_time_cap() {
        use ridge_ast::Capability;
        let b = builtins();
        let scheme = stdlib_signature(STD_TIME, "now", &b).unwrap();
        assert!(matches!(scheme.ty,
            Type::Fn { ref ret, ref caps, .. }
            if matches!(ret.as_ref(), Type::Con(id, _) if *id == b.timestamp)
            && matches!(caps, CapRow::Concrete(cs) if cs.contains(Capability::Time))
        ));
    }

    // ── std.random ────────────────────────────────────────────────────────────

    #[test]
    fn std_random_float_returns_float() {
        let b = builtins();
        let scheme = stdlib_signature(STD_RANDOM, "float", &b).unwrap();
        assert!(matches!(scheme.ty,
            Type::Fn { ref ret, .. }
            if matches!(ret.as_ref(), Type::Con(id, _) if *id == b.float)
        ));
    }

    // ── std.env ───────────────────────────────────────────────────────────────

    #[test]
    fn std_env_get_returns_option_text() {
        let b = builtins();
        let scheme = stdlib_signature(STD_ENV, "get", &b).unwrap();
        assert!(matches!(scheme.ty, Type::Fn { ref ret, .. }
            if matches!(ret.as_ref(), Type::Con(id, args)
                if *id == b.option
                && args.len() == 1
                && matches!(&args[0], Type::Con(tid, _) if *tid == b.text))
        ));
    }

    // ── std.cli ───────────────────────────────────────────────────────────────

    #[test]
    fn std_cli_exit_returns_unit() {
        let b = builtins();
        let scheme = stdlib_signature(STD_CLI, "exit", &b).unwrap();
        assert!(matches!(scheme.ty, Type::Fn { ref ret, .. }
            if matches!(ret.as_ref(), Type::Con(id, _) if *id == b.unit)
        ));
    }

    // ── std.proc ─────────────────────────────────────────────────────────────

    #[test]
    fn std_proc_run_returns_result() {
        let b = builtins();
        let scheme = stdlib_signature(STD_PROC, "run", &b).unwrap();
        assert!(matches!(scheme.ty, Type::Fn { ref ret, .. }
            if matches!(ret.as_ref(), Type::Con(id, _) if *id == b.result)
        ));
    }

    // ── std.json ──────────────────────────────────────────────────────────────

    #[test]
    fn std_json_encode_is_json_value_to_text() {
        let b = builtins();
        let scheme = stdlib_signature(STD_JSON, "encode", &b).unwrap();
        // encode : JsonValue -> Text
        assert!(scheme.vars.is_empty());
        assert!(matches!(
            &scheme.ty,
            Type::Fn { params, ret, .. }
                if params.len() == 1
                    && matches!(&params[0], Type::Con(id, _) if *id == b.json_value)
                    && matches!(ret.as_ref(), Type::Con(id, _) if *id == b.text)
        ));
    }

    #[test]
    fn std_json_decode_is_text_to_result_json_error() {
        let b = builtins();
        let scheme = stdlib_signature(STD_JSON, "decode", &b).unwrap();
        // decode : Text -> Result JsonValue Error
        assert!(scheme.vars.is_empty());
        let Type::Fn { params, ret, .. } = &scheme.ty else {
            panic!("decode must be a function type");
        };
        assert_eq!(params.len(), 1);
        assert!(matches!(&params[0], Type::Con(id, _) if *id == b.text));
        match ret.as_ref() {
            Type::Con(id, args) if *id == b.result => {
                assert!(matches!(&args[0], Type::Con(i, _) if *i == b.json_value));
                assert!(matches!(&args[1], Type::Con(i, _) if *i == b.error));
            }
            other => panic!("decode must return Result JsonValue Error, got {other:?}"),
        }
    }

    // ── std.net.http ──────────────────────────────────────────────────────────

    /// `listen` is the only `net.http` symbol that has a real Phase 4 signature
    /// (so `examples/url_shortener.ridge` can type-check); the other `net.http`
    /// items remain stubs (`Request`, `Response`, `respond`, `get`, …).
    #[test]
    fn std_net_http_listen_is_int_handler_to_unit() {
        let b = builtins();
        let scheme = stdlib_signature(STD_NET_HTTP, "listen", &b).unwrap();
        // Two schema-level vars: A (unused — reserved) and B_VAR (handler type).
        assert_eq!(scheme.vars.len(), 2);
        // Shape: Int -> handler -> Unit
        assert!(matches!(
            &scheme.ty,
            Type::Fn { params, ret, .. }
                if params.len() == 2
                    && matches!(&params[0], Type::Con(id, _) if *id == b.int)
                    && matches!(ret.as_ref(), Type::Con(id, _) if *id == b.unit)
        ));
    }

    #[test]
    fn std_net_http_request_is_phase7_stub() {
        let b = builtins();
        let scheme = stdlib_signature(STD_NET_HTTP, "Request", &b).unwrap();
        assert!(matches!(scheme.ty, Type::Error));
    }

    // ── unknown symbol returns None ───────────────────────────────────────────

    #[test]
    fn unknown_symbol_returns_none() {
        let b = builtins();
        assert!(stdlib_signature(STD_INT, "nonexistent", &b).is_none());
    }

    #[test]
    fn unknown_module_returns_none() {
        let b = builtins();
        assert!(stdlib_signature(StdlibModuleId(99), "toText", &b).is_none());
    }
}
