//! Ridge standard library — compiled artefacts and public facade.
//!
//! The build script (`build.rs`) discovers the `.ridge` source files under
//! `stdlib/`, drives the Ridge pipeline over them in tier order, and emits
//! generated tables into `OUT_DIR`.

#![deny(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
#![cfg_attr(test, allow(clippy::unwrap_used, clippy::expect_used, clippy::panic))]

pub mod build_driver;
pub mod codegen_ffi_targets;
pub mod codegen_manifest;
pub mod ffi_caps_audit;
pub mod ffi_targets;
pub mod ffi_validator;

use std::path::Path;

// `STDLIB_SOURCES: &[(&str, &str)]` — embedded source tree, generated by
// build.rs via `include_str!` over every `stdlib/**/*.ridge` file.
include!(concat!(env!("OUT_DIR"), "/stdlib_sources.rs"));

/// Unpack the embedded stdlib `.ridge` sources into `dest`.
///
/// Each entry in [`STDLIB_SOURCES`] is written to `dest/<relative_path>`,
/// creating parent directories as needed. The driver calls this on a
/// per-build tempdir before compiling the stdlib into BEAM artefacts, so
/// released binaries can ship the sources alongside the compiler rather
/// than depending on a build-time absolute path that only resolves on
/// the original build machine.
///
/// # Errors
///
/// Returns the first I/O error encountered while creating directories or
/// writing files under `dest`.
pub fn write_stdlib_sources_to(dest: &Path) -> std::io::Result<()> {
    for (rel, contents) in STDLIB_SOURCES {
        let path = dest.join(rel);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&path, contents)?;
    }
    Ok(())
}
